### ISSUE TITLE
Can't export rcp product while use pleiades(

### ISSUE THREAD

**Issue by mingchaoyang** [cypher256/pleiades.io#10]
Hi! I'm using pleiades for RCP develope with Japnaese. But when I try to export the RCP product use 'Eclipse product' define file, there is no reaction when I click 'Finish' button on Export dialog window. 
I will sucessed if I comment out pleiades plugin within the eclipse.ini. Reword, there is no problem in oroginal eclipse(with english UI).

Regards,
Yang

**Comment by cypher256** [comment]
Is it the dialog below?
![export_dialog](https://user-images.githubusercontent.com/1156871/49420892-f4602500-f7d0-11e8-82ff-6556f13f5716.png)

In the minimum configuration I tried, there was no situation where the finish button could not be pressed.
Could you please provide me with the minimum settings for reproducing?

**Comment by mingchaoyang** [comment]
Thanks for your replay, Kashihara san.
I resolved this situation while I found below message in workspace/.metadata/.log

!ENTRY org.eclipse.ui 4 0 2018-12-05 10:15:03.223
!MESSAGE 未処理のイベント・ループ例外
!STACK 0
java.lang.IllegalArgumentException: Index out of bounds
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4467)
	at org.eclipse.swt.SWT.error(SWT.java:4438)
	at org.eclipse.swt.widgets.Widget.error(Widget.java:448)
	at org.eclipse.swt.widgets.Combo.getItem(Combo.java:1057)
	at org.eclipse.pde.internal.ui.wizards.exports.ProductExportWizardPage.saveSettings(ProductExportWizardPage.java:204)
	at org.eclipse.pde.internal.ui.wizards.exports.BaseExportWizard.saveSettings(BaseExportWizard.java:82)

We must set the [ソースのエクスポート] combo even we don't need it. If leave the combo blank, the problem occur in pleiades enabled environment and not occur in original english.
I havn't idea for this strange thing but there is not a problem for me.
Thank you very much!

By the way, if pleiades can translation a RCP application for japanese?
I tried use pleiades setup.exe for my RCP application, but no effect(like menu, etc.).

Regards,

**Comment by cypher256** [comment]
I'm glad the problem was solved.
The problem when choosing "ソースのエクスポート" is unresolved, but I think it seems to be an Eclipse side problem.

> if pleiades can translation a RCP application for japanese?

Although it corresponds to STS etc, application which is not open to the public is out of the effective range because I can not confirm the operation.
