### ISSUE TITLE
Java18 サポート

### ISSUE THREAD

**Issue by happyhills** [cypher256/pleiades.io#100]
Eclipse 2022-03 は "Supports Java 18 via Eclipse Marketplace" とのことですが、
Pleiades All in One Eclipse ではこれを同梱してリリースする予定はありますでしょうか。

**Comment by cypher256** [comment]
Java 18 Support for Eclipse 2022-03 は近日追加予定です。
ただ、Java 18 自体の同梱は未定です。

**Comment by happyhills** [comment]
ご回答ありがとうございます。安心しました。リリースを待ちます。
