### ISSUE TITLE
F5等を押すと出てくるポップアップの消し方について

### ISSUE THREAD

**Issue by Riopika** [cypher256/pleiades.io#102]
F5等を押すと出てくるポップアップの消し方の方法をご教示ください。
![無題](https://user-images.githubusercontent.com/60454400/161690047-2a4c34e7-13e2-4439-ad2f-7d59d11c979e.jpg)

**Comment by cypher256** [comment]
下記チェックボックス 2 つを OFF にしてください。

* 設定 > 一般 > キー  の下部
  * キーボード
  * マウス・クリック

**Comment by Riopika** [comment]
ありがとうございます、助かりました。
