### ISSUE TITLE
Rebase a fork/フォークを元に戻す 

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#103]
Issue:
https://pleiades.io/help/idea/contribute-to-projects.html#rebase-fork
https://www.jetbrains.com/help/idea/contribute-to-projects.html#rebase-fork

"Rebase"が"元に戻す"と訳されているが、"リベース"または"Rebase（英語のまま）"のほうが一般的である思われる。

他のサイトの例：
https://git-scm.com/book/ja/v2/Git-%E3%81%AE%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E6%A9%9F%E8%83%BD-%E3%83%AA%E3%83%99%E3%83%BC%E3%82%B9
https://www.atlassian.com/ja/git/tutorials/merging-vs-rebasing

Actual:
フォークを元に戻す

Expected:
フォークをリベースする

**Comment by cypher256** [comment]
提案いただいた内容となるように修正し、反映しました。

> Expected:
> フォークをリベースする

また、同様の箇所が無いか確認しました。

**Comment by mhorioka** [comment]
ありがとうございます🙇‍♂️
