### ISSUE TITLE
pleiadesがダウンロードできない

### ISSUE THREAD

**Issue by tomo0858** [cypher256/pleiades.io#104]
お世話になります。

Pleiades All in One Eclipse 2019をダウンロードしたいのですが、「https://ftp.jaist.ac.jp/pub/mergedoc/pleiades/2019/pleiades-2019-12-ultimate-win-64bit-jre_20200213.zip」を開こうとするとページの更新に時間がかかり、
「このサイトにアクセスできません
ftp.jaist.ac.jp からの応答時間が長すぎます。」
と表示され、ダウンロードができません。
解決策はありますでしょうか。

よろしくお願いいたします。

**Comment by cypher256** [comment]
JAIST 停電中みたいです。
http://www.jaist.ac.jp/

ページ右上のミラーサーバ選択で
pleiades.io
を選択して、ダウンロードしてみてください。

**Comment by tomo0858** [comment]
できました。
ありがとうございました。
