### ISSUE TITLE
m2e-wtpプラグインについて

### ISSUE THREAD

**Issue by hobbydick** [cypher256/pleiades.io#105]
Pleiades All in One Eclipse Java Full Editionについて質問がございます。
リリース 2020-12
リリース 2021-12
ともに、m2e-wtpプラグイン（バージョン1.4.4）がインストールされていましたが、
リリース 2022-06
では、m2e-wtpプラグインがインストールされていませんでした。
これはなぜでしょうか？

**Comment by cypher256** [comment]
下記に含まれています。
eclipse/dropins/M2E-APT

また、メニューの 設定 > Maven の下に
注釈処理
が表示されているかと思います。

バージョン情報を開いて、
インストール詳細ボタン >
フィルターに m2e と入力することでも確認できます。

**Comment by hobbydick** [comment]
回答ありがとうございます。
おっしゃられる通り、インストール詳細よりm2eと検索すると、リリース 2022-06でも検索がヒットいたします。
しかしながら、
m2e-wtp
で検索しますと、
リリース 2020-12
リリース 2021-12
では検索がヒットいたしますが、
リリース 2022-06ではヒットいたしません。
フィーチャータブのフィーチャーIDで申しますと、
リリース 2020-12
リリース 2021-12
においては、
org.eclipse.m2e.feature
org.eclipse.m2e.wtp.feature
の両方がインストールされていたのですが、
リリース 2022-06
におきましては、
org.eclipse.m2e.wtp.feature
がインストールされていないようなのです。

**Comment by cypher256** [comment]
失礼しました。足りないですね。

### 経緯
容量を削減するために Pleiades All in One Java 2022 からベースの Eclipse パッケージを変更

* 2021 以前: Eclipse IDE for Enterprise Java and Web Developers
* 2022 以降: Eclipse IDE for Java Developers

代わりに WTP 関連は dropins/WTP に別途追加で格納。
そのときに今回ご指摘のプラグインが不足していました。

### 対応
dropins/WTP に下記を追加
* m2e-wtp - Maven Integration for WTP

### 確認
対応したものを下記にアップロードしました。
できれば問題ないか見てもらえませんか？ 問題ないようでしたら正式版としてリリースします。
（Windows ですよね）
http://download.pleiades.io/download/pleiades/2022/pleiades-2022-06-java-win-64bit-jre_20220515_test.exe

### 参考
ベースの Eclipse に追加する WTP の機能 (m2e-wtp は今回追加)
![s1](https://user-images.githubusercontent.com/1156871/168460154-fbf0ae60-0069-4533-ae42-1c296bacf86a.png)

今回対応後のインストール詳細
![s2](https://user-images.githubusercontent.com/1156871/168460174-6ea6226e-2a32-4c02-b137-3d0188d1166f.png)

**Comment by hobbydick** [comment]
はい。Windows10です。
ダウンロードして確認いたしました。
m2e-wtpがインストールされており、正しく動作することを確認いたしました。
ありがとうございます。
