### ISSUE TITLE
誤訳：ナチスファイル

### ISSUE THREAD

**Issue by n-suudai** [cypher256/pleiades.io#106]
[こちらのページ](https://pleiades.io/help/resharper/Debugging_Assistance_in_CPP.html#inline-values)の一部に誤訳が見つかったので報告します。
- [ナチス(英語)](https://msdn.microsoft.com/en-us/library/jj620914.aspx)ファイル -> [.natvis(英語)](https://msdn.microsoft.com/en-us/library/jj620914.aspx)ファイル

>Expected

ReSharper は、Visual Studio デバッガーエンジンを使用してインライン値を計算し、式を評価することに注意してください。つまり、ユーザーが指定した視覚化ルールを持つ[ナチス(英語)](https://msdn.microsoft.com/en-us/library/jj620914.aspx)ファイルが自動的にサポートされます。

>Actual

ReSharper は、Visual Studio デバッガーエンジンを使用してインライン値を計算し、式を評価することに注意してください。つまり、ユーザーが指定した視覚化ルールを持つ[.natvis(英語)](https://msdn.microsoft.com/en-us/library/jj620914.aspx)ファイルが自動的にサポートされます。

**Comment by cypher256** [comment]
ありがとうございます。まずい訳になってますね。。。
原文のまま下記のとおり、Natvis となるように修正しました。

ReSharper は、Visual Studio デバッガーエンジンを使用してインライン値を計算し、式を評価することに注意してください。つまり、ユーザーが指定した視覚化ルールを持つ [Natvis(英語)](https://msdn.microsoft.com/en-us/library/jj620914.aspx) ファイルが自動的にサポートされます。
