### ISSUE TITLE
"Pleiades [カスタム]"設定で、Javaソースコメントがフォーマット対象となる場合がある

### ISSUE THREAD

**Issue by WhiteNoise0000** [cypher256/pleiades.io#107]
いつもお世話になっております。
些細な点ですが、おそらく意図に反するJavaフォーマッタの挙動を検知したためご報告です。
→こういった場でご報告を上げる経験に乏しく、ほかに必要な情報などある場合はお申し付けください。

## 報告事象
 "Pleiades [カスタム]"の設定に反し、各種コメントにフォーマッタが適用される場合がある

## 再現確認バージョン
- Eclipse Kepler (pleiades-e4.3-java-32bit-jre_20140321)
- Eclipse 2022 (pleiades-2022-06-java-win-64bit-jre_20220515)

## 再現確認手順
1. 存在しない workspaceパスを指定し、Eclipseを起動
2. 適当なJavaプロジェクト、Javaクラスを新規作成
3. 適当な行コメントを記入し、末尾半角SPを入力
※デフォルトの"Pleiades [カスタム]"では、フォーマット対象外
4. Ctrl + Shift + F でJavaフォーマッタを適用
5. "Pleiades [カスタム]"の設定に反し、行コメントにフォーマッタが適用される（末尾の半角SPトリム）

## 当方での確認情報
- ワークスペース設定画面上は"Pleiades [カスタム]"がデフォルト設定と表示されますが、
上記事象発生時は"Eclipse [ビルドイン]"でのフォーマットとなっているようです
- "Pleiades [カスタム]"プロファイルの編集画面を一度開き、
何も編集せずOK → 「適用して閉じる」ボタンを押下後に、期待する挙動（コメントフォーマット対象外）に変化しました

## 推定する原因
- 「適用して閉じる」ボタン押下前後で、下記prefs内に「org.eclipse.jdt.core.formatter.*」が追記されていました。
".metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.jdt.core.prefs"
- 「org.eclipse.jdt.core.formatter.*」ですが、.metadata.default配下の「org.eclipse.jdt.core.prefs」には未定義でした

## 参考ファイル
1. [org.eclipse.jdt.core.prefs.txt (新規作成直後)](https://github.com/cypher256/pleiades.io/files/8730111/_org.eclipse.jdt.core.prefs.txt)
2. [org.eclipse.jdt.core.prefs.txt (適用して閉じる押下後)](https://github.com/cypher256/pleiades.io/files/8730146/_org.eclipse.jdt.core.prefs.txt)

**Comment by cypher256** [comment]
> 再現確認手順
> 当方での確認情報
> 推定する原因

すばらしい。原因まで特定いただき助かりました。
下記ご指摘に従い .metadata.default の未定義部分を追加したものを、次回リリースに反映します。

> - 「適用して閉じる」ボタン押下前後で、下記prefs内に「org.eclipse.jdt.core.formatter.*」が追記されていました。
> ".metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.jdt.core.prefs"
> - 「org.eclipse.jdt.core.formatter.*」ですが、.metadata.default配下の「org.eclipse.jdt.core.prefs」には未定義でした
