### ISSUE TITLE
JetBrainsヘルプサイト 誤訳：PyCharm docstringの構文説明 Booを返す Foo と Bar の関数

### ISSUE THREAD

**Issue by Yumihiki** [cypher256/pleiades.io#109]
<img width="576" alt="スクリーンショット 2022-05-22 7 15 02" src="https://user-images.githubusercontent.com/41376154/169670638-55f9831a-84c8-41c3-a6de-b3802c7ab204.png">
日本語訳のサイト、とても助けられています。ありがとうございます！

[docstring のレガシー型構文](https://pleiades.io/help/pycharm/type-syntax-for-docstrings.html) が誤っていそうでしたのでご連絡です。

誤：
> Boo を返す Foo と Bar の関数

正：
> Baz を返す Foo と Bar の関数

**Comment by cypher256** [comment]
ありがとうございます。
ご指摘箇所の修正と、他、全般的に下記の訳しすぎ部分を修正しました。
* フー → Foo
* バー → Bar
