### ISSUE TITLE
pycharm tutorial でapplication名 pollsが世論調査と訳されている

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#11]
URL:
日本語
https://pleiades.io/help/pycharm/creating-and-running-your-first-django-project.html

英語
https://www.jetbrains.com/help/pycharm/creating-and-running-your-first-django-project.html

問題１
「次に、詳細設定ノードを展開し、Django関連の設定を指定します。アプリケーション名フィールドには、アプリケーション名（ここでは世論調査）を指定します。」

期待値：「世論調査」 はアプリケーション名なので訳さずに「polls」

問題２
つまり、Djangoに2つの新しいモデル選択と質問が作成され、移行が作成されたことを伝えました。

期待値：「選択」　「質問」　はモデル名　なので訳さずに　Choice　と Question

問題３
「実行 / Dug Configuration」ダイアログボックスでは、この実行/デバッグ設定に名前（ここでは mysite）を与え

期待値：Dugのところが変（もとの英語も変 https://youtrack.jetbrains.com/issue/PY-33013 ）
　リンク先を参照するかぎり、「実行 / デバッグ構成」

問題４
「ログインすると、管理ページが表示されます。認証と承認（グループとユーザー）セクションがありますが、ポーリングは使用できません。なぜそうなのか？」

期待値:ポーリング は polls

**Comment by cypher256** [comment]
> 問題１
> 「次に、詳細設定ノードを展開し、Django関連の設定を指定します。アプリケーション名フィールドには、アプリケーション名（ここでは世論調査）を指定します。」
> 期待値：「世論調査」 はアプリケーション名なので訳さずに「polls」

polls をインライン翻訳除外し、文章全体を考慮して翻訳するようにしました。

> 問題２
> つまり、Djangoに2つの新しいモデル選択と質問が作成され、移行が作成されたことを伝えました。
> 期待値：「選択」　「質問」　はモデル名　なので訳さずに　Choice　と Question

AppCode 新機能ページでメニュー文字列を後翻訳するようにしたことによるデグレード
修正しました。

> 問題３
> 「実行 / Dug Configuration」ダイアログボックスでは、この実行/デバッグ設定に名前（ここでは mysite）を与え
> 期待値：Dugのところが変（もとの英語も変 https://youtrack.jetbrains.com/issue/PY-33013 ）
> 　リンク先を参照するかぎり、「実行 / デバッグ構成」

変更元が修正されたため、対応されました。

> 問題４
> 「ログインすると、管理ページが表示されます。認証と承認（グループとユーザー）セクションがありますが、ポーリングは使用できません。なぜそうなのか？」
> 期待値:ポーリング は polls

Polls をインライン翻訳除外し、文章全体を考慮して翻訳するようにしました。
→ 訳は 投票 としました。

追加修正
ポーリングのリスト（インデックスページ）を含むページにアクセスする最も簡単な方法はURLを指定することです
修正：ポーリングのリスト → 投票のリスト

**Comment by mhorioka** [comment]
ありがとうございます。
