### ISSUE TITLE
pleiades-2022-06-java-win-64bit-jre_20220618.exeの自己解凍書庫実行時にエラー

### ISSUE THREAD

**Issue by GreatChida** [cypher256/pleiades.io#110]
いつもありがとうございます。

pleiades-2022-06-java-win-64bit-jre_20220618.exeの自己解凍書庫実行時に、下記エラーが出ます。
添付画像もご参考ください。

試したPCは2台、Windows11とWindows10です。
7-Zipでの解凍ではエラー等出ませんでした。

c:\pleiades\2022-06 フォルダにファイルを解凍しています
pleiades-2022-06-java-win-64bit-jre_20220618.exe から解凍しています
eclipse\dropins\STS\eclipse\plugins\org.springframework.tooling.boot.ls_1.34.0.202206140708\servers\spring-boot-language-server\META-INF\third-party-open-source-licenses\bsd 3-clause "new" or "revised" license (bsd-3-clause) - apl-v10.html を作成できません

<img width="388" alt="スクリーンショット 2022-06-18 115506" src="https://user-images.githubusercontent.com/22382968/174420657-f18d9768-ce80-4101-a8fc-1f8bdd1293d1.png">

**Comment by cypher256** [comment]
解凍後の Eclipse 動作には問題ありませんが、パスが長すぎるため解凍エラーになっていました。
パスが制限内になるように調整して、リリースしました。

**Comment by GreatChida** [comment]
早速のご対応ありがとうございます。
現象が修正されたのを確認いたしました。
