### ISSUE TITLE
プロパティ・ファイル・エディターがダブルバイト文字をUnicodeエスケープ形式へエンコード・デコードしてくれない

### ISSUE THREAD

**Issue by holyblue-jp** [cypher256/pleiades.io#111]
いつもありがとうございます。

「pleiades-2022-06-java-win-64bit-jre_20220619.exe」をダウンロードして利用しているのですが、
.propertiesファイルをプロパティ・ファイル・エディターで開いて保存しても、ダブルバイト文字をUnicodeエスケープ形式へエンコードしてくれません。
また反対にUnicodeエスケープ形式で記載された.propertiesファイルをプロパティ・ファイル・エディターで開いても、デコードしてくれません。

![image](https://user-images.githubusercontent.com/78884984/178688402-5f055544-68e4-437b-93bb-984f06235ca4.png)

試しにマーケットプレースから「SimplePropertiesEditor」をインストールしたところ、これだとダブルバイト文字⇔Unicodeエスケープ形式のエンコード・デコードが行われる事を確認できました。

![image](https://user-images.githubusercontent.com/78884984/178688882-6ff00eac-7cc8-4037-9e91-25e55b564045.png)

プロパティ・ファイル・エディターに何か追加で設定が必要であれば教えて頂けないでしょうか？

以上、宜しくお願い致します。

**Comment by cypher256** [comment]
### 個別に右クリックで選択する方法
properties ファイル > 右クリック > 次で開く から 3 種類のエディターが選択できます。
* Limy プロパティー・エディター (native2ascii)
* プロパティー・ファイル・エディター [Eclipse 標準]
* 汎用エディター - Spring Properties [STS 付属]
<img width="740" alt="a1" src="https://user-images.githubusercontent.com/1156871/178720753-d163c661-e2d8-4df9-907b-3f9ee054fc70.png">

Unicode エスケープされるのは Limy です。
上記で選択した後は、同じファイルは、選択したエディターで開かれます。
デフォルトは以下の理由により Eclipse 標準のプロパティー・エディターになっています。
* Java 標準 ResourceBundle プロパティファイルが UTF-8 になった
* Java も UTF-8 に統一する方向になっている

<br>

### 全体の設定を変更する方法
下記でデフォルトで開くエディターを変更できます。(選択してデフォルトボタンを押す)

<img width="833" alt="a2" src="https://user-images.githubusercontent.com/1156871/178720763-e83a90a0-9781-43ea-ab8f-9c52735d6c34.png">

**Comment by holyblue-jp** [comment]
ご回答ありがとうございます。

>デフォルトは以下の理由により Eclipse 標準のプロパティー・エディターになっています。
>・Java 標準 ResourceBundle プロパティファイルが UTF-8 になった
>・Java も UTF-8 に統一する方向になっている

上記について、経緯も含めてご説明頂きありがとうございます。
私の知識不足でした。

ご教授頂きました「Limyプロパティエディター」を用いれば、
Unicodeエスケープ形式がデコードして正しいダブルバイト文字で表示される事を確認できました。

今回J2EEの勉強をしていたのですが、Payara Server v5.2022.2のエラーメッセージを変更するプロパティファイルでは
UTF-8で書いたところ画面上でエラーメッセージが文字化けになってしまっていたので、
プロパティーファイルの文字コードはまだUnicodeエスケープ形式とUTF-8への移行段階なのだなと理解しました。

当分はケースバイケースでエディターを使い分けて行きたいと思います。

改めて今回はご回答頂きましてありがとうございました。

以上、宜しくお願い致します。

**Comment by holyblue-jp** [comment]
問題が解決しましたので、本件をクローズ致します。
