### ISSUE TITLE
H2 向けの設定について

### ISSUE THREAD

**Issue by mahata** [cypher256/pleiades.io#112]
翻訳ページの提供、どうもありがとうございます。

[Kotlin で Spring Boot Web アプリケーションの作成](https://spring.pleiades.io/guides/tutorials/spring-boot-kotlin/) を読み進めていたところ、H2 が `Error executing DDL "drop table if exists user CASCADE " via JDBC Statement` のようなエラーを吐いてうまく動かないようでした。

[翻訳元記事](https://raw.githubusercontent.com/spring-guides/tut-spring-boot-kotlin/b6ed535e3d4b6734a5695c32cc23ce8d5524b3eb/README.adoc)のように `application.properties` に次の二行を足すことで動かすことができました。

```
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.properties.hibernate.globally_quoted_identifiers_skip_column_definitions = true
```

これらは H2 の新しめのバージョンに対応するために翻訳元で後から追記されたもののようですが、よかったら翻訳記事にも反映していただけるといいかもしれないです。

**Comment by cypher256** [comment]
キャッシュが 86400 秒で、その後に取得するため、元ページが変更されからだいたい 1〜2 日で反映されます。
反映されない場合は、ブラウザのリロードを試してみてください。
