### ISSUE TITLE
Spring Securityのユーザー名とパスワードの読み取りページの誤訳

### ISSUE THREAD

**Issue by dkurata38** [cypher256/pleiades.io#113]
いつもSpringの日本語訳ドキュメントを利用させていただいています。

[ユーザー名とパスワードの読み取り](https://spring.pleiades.io/spring-security/reference/servlet/authentication/passwords/input.html)にて、「フォーム」が「書式」と訳されています。

「書式」というリンクをクリックした先のページでは「フォームログイン」という言葉が使われているので、「書式」ではなく「フォーム」と訳した方がいいと思いました。

**Comment by cypher256** [comment]
ありがとうございます。修正しました。
再読み込みで反映されると思います。

**Comment by dkurata38** [comment]
迅速なご対応ありがとうございます。
無事に確認できました。
