### ISSUE TITLE
コンテンツ・アシストが一部表示されない

### ISSUE THREAD

**Issue by Riopika** [cypher256/pleiades.io#114]
Ctrl + Spaceでコンテンツ・アシストが表示されますが、tryやfor等を入力してコンテンツ・アシストを表示しようとしても何も表示されません。
また、forを入力してコンテンツ・アシストを表示しようとすると@formatter:offが設定からOFFにしているのにも関わらずソース上に出力されてしまいます。
原因をご教示ください。
なお、Eclipseは最新バージョンになります
![コンテンツ・アシスト](https://user-images.githubusercontent.com/60454400/183317425-7a2fe1f3-7a73-4520-877e-dd7602e6110e.jpg)
![formatter](https://user-images.githubusercontent.com/60454400/183317430-a51566a1-e9f9-41f4-b6ea-b11b942bc85a.jpg)
。

**Comment by cypher256** [comment]
下記を解凍直後にプロジェクト作成後、for でコンテンツアシストが動作しました。
何らかの環境依存による問題が発生しているのかもしれません。
pleiades-2022-06-java-win-64bit-jre_20220619.exe

![a1](https://user-images.githubusercontent.com/1156871/183410294-549d0061-0d23-46e0-b642-1e59285fbb79.png)
![a2](https://user-images.githubusercontent.com/1156871/183410306-ce2bed35-d3f6-44b7-89aa-0d5facadb682.png)

**Comment by Riopika** [comment]
Eclipseをインストールし直すと正常に動作しました。
ありがとうございました。
