### ISSUE TITLE
TeamCityのマニュアル: Preliminariesが予選と訳されている

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#116]
**場所**
日本語
https://pleiades.io/help/teamcity/install-and-start-teamcity-server.html#Preliminaries
英語
https://www.jetbrains.com/help/teamcity/install-and-start-teamcity-server.html#Preliminaries

**Actual**
予選﻿　<-ここ
サーバーをインストールする前に、次のことを確認してください。

Preliminaries﻿
Before installing the server, make sure to:

**Suggestion**

「準備」
等のほうが適切であると思われる
https://ejje.weblio.jp/content/preliminaries

**Comment by cypher256** [comment]
ご指摘ありがとうございます。
Preliminaries﻿ の訳を「予選」から「準備」に修正しました。

**Comment by mhorioka** [comment]
ありがとうございます！確認しました。
