### ISSUE TITLE
Javaインスペクションのデフォルト状態{Enabled, Disabled} {使用可能, 使用不可「}

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#117]

**Comment by mhorioka** [comment]
箇所
https://pleiades.io/help/idea/list-of-java-inspections.html

提案
インスペクションのデフォルト状態の
Enabled, Disabledの訳は「使用可能」「 使用不可」でも通じなくはないと思いますが、「有効」「無効」の方が自然であると思います（他の箇所への影響はあるかもしれませんが。。。）

**Comment by cypher256** [comment]
ありがとうございます。対応しました。
以下の経緯があり、そうなっていました。

* Eclipse の翻訳で上書きされていた
* 基本は IntelliJ ヘルプから取り込んだものを優先しているが単語はコンテキスト依存のため、単語はコンテキスト非依存ベースの Pleiades 訳を使用していた
* Eclipse の翻訳の該当 2 つは、IBM 翻訳ルールとして統一されており、10 年以上前から既知の問題で「有効」「無効」が妥当と感じていたが、影響範囲の大きさでチェックできず保留されてきた
* 10 年以上、多くの翻訳メンバや利用者から指摘がなかった (致命的でない場合は IBM 翻訳踏襲だった)

該当ページはキャッシュを消したため、すでに反映されています。
他のページは反映されるまで、最大 1 日かかります。

**Comment by mhorioka** [comment]
ありがとうございます！
