### ISSUE TITLE
https://pleiades.io/help/idea にアクセスできない

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#118]
一時的かもしれませんが https://pleiades.io/help/idea にアクセスすると

50x Error

と表示されます。

**Comment by cypher256** [comment]
対応して、復旧しました。
原因が特定できていませんが、一時期にディスク I/O が増大し、自動復旧もできない状態になっていました。
現在は正常稼働しています。

**Comment by mhorioka** [comment]
ありがとうございます！

**Comment by mhorioka** [comment]
2022/11/28 12:07の時点ですが、問題が発生しているようです。

**Comment by cypher256** [comment]
参照している DNS サーバに問題が発生していたようで、特に対応なしで現在は回復しているようです。

**Comment by mhorioka** [comment]
本日以前と同じような問題（DNS?)が発生しているようです。
https://pleiades.io/ はOKですが、その下の各製品ページが50x Errorになります。

**Comment by cypher256** [comment]
調子が悪い？ようなので、再起動して対応しました。

**Comment by mhorioka** [comment]
調査および修正ありがとうございます！

**Comment by mhorioka** [comment]
https://pleiades.io/help/phpstorm が現在アクセスできないようです

**Comment by cypher256** [comment]
ご連絡ありがとうございます。対応しました〜。
