### ISSUE TITLE
YouTrack: salted が 塩味の

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#119]
Actual:
https://pleiades.io/help/youtrack/cloud/Security.html#database-encryption

YouTrack はパスワードを**塩味の**ハッシュとしてデータベースに保存します。各ユーザーのパスワードは、異なるランダム化されたソルトでハッシュされます。**塩味の**パスワードは、SHA-256 暗号化ハッシュ関数を使用してハッシュされます。

英語：
https://www.jetbrains.com/help/youtrack/cloud/Security.html#database-encryption

Suggested:

salted は 「ソルト付き」や「ソルト化」が良いと思われる

**Comment by cypher256** [comment]
ありがとうございます。
「ソルト付き」としました。

**Comment by mhorioka** [comment]
ありがとうございました！
