### ISSUE TITLE
ショートカットキーの説明において、Win(Windowsのショートカットキーの説明)が 「勝ち」と翻訳されている

### ISSUE THREAD

**Issue by kei-q** [cypher256/pleiades.io#12]
こちらwindowsとmacOSのショートカットキーの説明ですが、windowsのショートカットキーの説明部分で `Win` が翻訳されてしまっています。

## 該当ページ

https://pleiades.io/help/pycharm/ipython-notebook-support.html
確認していませんが、他のショートカットキーを紹介しているページも同様かもしれません

## screenshot

![screenshot from 2019-01-28 23-55-14](https://user-images.githubusercontent.com/58161/51844284-341e3580-2358-11e9-926a-1e4c7c817e81.png)

![screenshot from 2019-01-28 23-55-20](https://user-images.githubusercontent.com/58161/51844285-341e3580-2358-11e9-8160-5cdd4284bf1b.png)

**Comment by cypher256** [comment]
以下を翻訳エンジン全体に適用しました。
- Win を翻訳禁止ワードに ("勝つ" という意味で使用されたとしても未翻訳で良いと判断)
- Ability: 〜能力 → 〜機能 (今後調整する可能性あり)
- プレス [キー名] → [キー名] 押下
