### ISSUE TITLE
Pleiades 2022.10.18版をダウンロードできない

### ISSUE THREAD

**Issue by shirayuki** [cypher256/pleiades.io#120]
Pleiadesプラグインの2022.10.18版がリリースされたことになっているのに、2022.09.14版がダウンロードされます。

**Comment by cypher256** [comment]
アップロードに失敗していました。数時間後に反映されます。
すぐに必要な場合、下記から  2022.10.18版がダウンロードできます。

https://mergedoc.osdn.jp/pleiades-redirect/pleiades-win.zip.html
https://mergedoc.osdn.jp/pleiades-redirect/pleiades-mac.zip.html
https://mergedoc.osdn.jp/pleiades-redirect/pleiades.zip.html

**Comment by shirayuki** [comment]
確認できました。ありがとうございました。
