### ISSUE TITLE
Pleiades All in Oneの起動時にjava17を要求される

### ISSUE THREAD

**Issue by ry-suzuki** [cypher256/pleiades.io#125]
jdk11がインストールされている環境でPleiades All in One JavaのStandard Edition(2022-12.20230124)を使用しようとしたところ、java17以降を要求されて起動することができませんでした。
```
Version 11.0.2 of the JVM is not suitable for this product. Version: 17 or greater is required.
```

動作環境として、Pleiadesプラグイン本体はjava11以上との記載がありますが、
Pleiades All in Oneについてはjava17以上が必須ということでしょうか？

**Comment by cypher256** [comment]
eclipse.ini の下記の設定を 11 に変更して起動してみてください。
`-Dosgi.requiredJavaVersion=17`

eclipse 2022 では 11 が正しい値で、Pleiades All in One の設定が間違っていました。
17 に変更して再リリース予定です。

**Comment by ry-suzuki** [comment]
eclipse.iniを11に変更したところ、起動することができました。
ありがとうございました。

**Comment by cypher256** [comment]
Eclipse 本体の要件は Java 11 なのですが、
STS などのプラグインが動作していないことが判明したため、
下記 eclipse.ini 定義の起動チェック最低バージョンを 17 に戻してリリース予定です。
`-Dosgi.requiredJavaVersion=17`

Eclipse 要件は Java 11
https://wiki.eclipse.org/Eclipse/Installation#Install_a_JVM

LSP4E 要件は Java 17 (STS、WWD、TM4E などが使用)
https://github.com/eclipse/lsp4e/issues/326

**Comment by ry-suzuki** [comment]
ありがとうございます。
Pleiades All in Oneは今後はjava17以降が必要であり、
java11の環境でStandard EditionのPleiades All in Oneを使用したい場合には
2021-12リリース以前のものを使用するしかないという認識であっているでしょうか？

**Comment by cypher256** [comment]
> java11の環境でStandard EditionのPleiades All in Oneを使用したい場合には
> 2021-12リリース以前のものを使用するしかないという認識であっているでしょうか？

はい、そうなると思います。

**Comment by ry-suzuki** [comment]
承知しました。
ご回答ありがとうございました。
