### ISSUE TITLE
リソース名の変更にものすごく時間がかかる

### ISSUE THREAD

**Issue by rg-jp** [cypher256/pleiades.io#126]
ソースファイル(*.java、*.js、*.html、*.css など種類は問いません）をコピー＆ペーストして、ペーストしたファイルの名前を変更しようとすると、次の状態のまま、ものすごく時間がかかります。
![image](https://user-images.githubusercontent.com/91297298/219559104-cc5b9fed-65ca-4cc2-88dc-527ae9962ed7.png)
2回目以降はすぐに完了しますが、しばらく時間をおくと、また同じ現象になります。
かなりストレスなのですが、考えられる原因はなんでしょうか。

**Comment by cypher256** [comment]
再現できていないのですが、下記ではありませんか？
#124 Pleiades All in One 2022-12 が重い・遅い・フリーズする

**Comment by rg-jp** [comment]
> 1. 設定 > 言語サーバー > Spring 言語サーバー > Spring Boot 言語サーバー > OpenRewrite > Java ソースの調整 : OFF
> 2. STS プラグインバージョンアップ 4.17.0 → 4.17.1 https://download.springsource.com/release/TOOLS/sts4/update/latest/
> 3. Pleiades All in One 2022-12.20230124 以降のリリースを再インストール (STS バージョンアップ 版)

1と2は試してみました。
2.はSTS関係は全て、4.17.2 です。
でも、改善されません。
3 を試してみます。

**Comment by rg-jp** [comment]
2022-12の最新版で試してみたところ、発生しなくなりました。
これで様子をみてみます。
ありがとうございました。
