### ISSUE TITLE
Platform 版にマーケットプレース・クライアントをインストールしてもメニューに表示されない

### ISSUE THREAD

**Issue by kizcaw** [cypher256/pleiades.io#128]
クリーン・インストールをしたく、pleiades-2022-12-platform-win-64bit_20230212 をダウンロード。
起動直後に、新規ソフトウェアのインストール... から、マーケットプレース・クライアントをインストール。
再起動を求められるので、再起動するのが、ヘルプ配下に「Eclipse マーケットプレイス」が表示されません。
![インストール済のソフトウェア](https://user-images.githubusercontent.com/30107554/223283993-0e01d060-8661-4821-96d2-5e3673ac1589.png)

**Comment by cypher256** [comment]
デフォルトで登録されている更新サイトのマーケットプレース・クライアント 1.10.1 ではなく、
クリーンインストールして、下記の 1.10.0 の更新サイト URL を指定してインストールしてみてください。
https://download.eclipse.org/mpc/releases/1.10.0

![image](https://user-images.githubusercontent.com/1156871/223287184-03fadf49-9b46-4d22-ba3b-496ab0f4ccbd.png)

**Comment by kizcaw** [comment]
ありがとうございます。

再度クリーンな状態から、ご指定の方法で試したのですが、結果は変わらずでした。
さらに前の v1.9.2 や v1.9.3 でも試しましたがダメでした。

ちなみに、2021 と v1.9.2 の組み合わせなら問題なく表示されました。
![インストール済のソフトウェア2](https://user-images.githubusercontent.com/30107554/223297169-a601873d-06d2-470a-9b1b-27ed62524e1e.png)
![インストール済のソフトウェア3](https://user-images.githubusercontent.com/30107554/223297180-9c327ddb-a238-48b8-9549-4912944e7239.png)
![インストール済のソフトウェア4](https://user-images.githubusercontent.com/30107554/223297185-3ce440a9-5e34-463b-84b7-de87792d074a.png)

**Comment by cypher256** [comment]
こちらでは動作するので、環境の問題かもしれませんね。

Windows 10 Pro 21H2
pleiades-2022-12-platform-win-64bit_20230212.exe
マーケットプレース・クライアント 1.10.0

java -version
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)

![image](https://user-images.githubusercontent.com/1156871/223314723-c9ea0052-7ab8-46ed-b6eb-8c1d28bb5da7.png)

**Comment by kizcaw** [comment]
わざわざ検証して頂いて本当にありがとうございます。

別の端末でも試したのですがダメでした。

Windows 10 Pro 22H2 (別の端末: Windows 10 Home 21H2)
JDK 17.0.4 2022-07-19 (Temurin-17.0.4+8, HotSpot)

JDK を 17.0.6 にして試してみます。
少し出かけるので結果報告は遅くなるかもですが、必ず報告します。m(_ _)m

**Comment by kizcaw** [comment]
JDK Temurin-17.0.6+10 (2023-01-17) で試しましたが、やっぱりダメでした。
う～ん、これまで Eclipse は何度もセットアップしてきたのですが、今回のような現象は初めてですねー。

あとできそうな検証としては、Platform 版にマケプレだけをインストールして固めたものを実行するくらいでしょうか。

**Comment by cypher256** [comment]
すでに試されているかもしれませんが、考えられる対応としては下記があります。

- -clean 起動
- 既存の workspace を使用している場合は、新しい workspace で起動
- ウィンドウ > パースペクティブ > パースペクティブのリセット
- 「エラー・ログ」ビューを開いてなんかエラーが出てないか
- eclipse.ini の -javaagent 行を削除 (Pleiades を無効化) して、起動

同じ症状が報告されているが未解決
https://www.eclipse.org/forums/index.php/t/1111940/

もし面倒でなければ下記のように自分で構築 (解決できるかは不明)

1. 本家 eclipse-platform-4.26-win32-x86_64.zip をダウンロードして解凍
https://download.eclipse.org/eclipse/downloads/drops4/R-4.26-202211231800/#PlatformRuntime
1. 素の状態でマーケットプレース・クライアントをインストールしてみる
1. Pleides All in One に近い状態にするには下記などを Pleiades All in One からコピー
.metadata.default --- workspace 作成時に workspace 配下にデフォルト設定としてコピーされる
eclipse/configuration
eclipse/dropins

**Comment by kizcaw** [comment]
詳細なご指示、ありがとうございます。

-clean 起動と workspace のクリーンは毎回やっています。
-javaagent 行の削除、Pleiades の適用なしでやってみましたがダメでした。

本家 Eclipse は時間がなくて試していないのですが、Eclipse のフォーラムを見る感じだと Eclipse 本体の問題ですかねー。
こちらで ISSUE を出してしまったこと、お詫び申し上げます。

本日中に環境を整えないといけないので、一旦は 2021 の方で構築します。
お詫びといってはアレですが、落ち着いたら、最新版の 2023 で再挑戦して報告いたします。

**Comment by cypher256** [comment]
本チケットとしてはクローズします。
