### ISSUE TITLE
Pleiades all-in-one 2022-03 20230212 for Mac Java Full VersionでサーバーパネルからTomcat9(Java11)が起動しない

### ISSUE THREAD

**Issue by YukinobuYoshihara** [cypher256/pleiades.io#129]
## バージョン
- Pleiades all-in-one 2022-03 20230212 for Mac Java Full Version
## 症状
- インストール直後の状態でプロジェクトは一切なし
- サーバーパネルからTomcat9_Java11を起動
- 進行状況が起動委譲の準備中・・・仮想マシンを開始中のまま
- 45秒経過すると「問題が発生、45秒以内に起動できませんでした」と表示
<img width="692" alt="skitch" src="https://user-images.githubusercontent.com/3235165/224303707-05d715f8-ee55-438a-9221-653bc190dd56.png">

## 試したこと
- タイムアウトを倍の90秒に伸ばしてみる→ダメ
- /Applications/Eclipse_2022-12.app/Contents/tomcat/9以下のstartup.shを直接起動 → ちゃんとtomcatが起動する →Tomcat Managerアプリもアクセスを確認

- よろしくお願い申し上げます。

**Comment by cypher256** [comment]
Intel macOS Monterey 12.6.3 (21G419)
pleiades-2022-12-java-mac-jre_20230212.dmg クリーンインストール

![image](https://user-images.githubusercontent.com/1156871/224458214-dc53a546-01fa-47e2-98a8-1bce92e1761b.png)

こちらでは起動できました。
スクショから Boot ダッシュボードビューが壊れているように見えるので、全体的になにか問題が発生してそうです。
サーバービューから定義を削除して、サーバー定義を作り直しても、解消しませんか？

**Comment by YukinobuYoshihara** [comment]
@cypher256 
ご返答ありがとうございます。
- MacBook Air (M2,2022) Monterey 12.6.1
- MacBook Air (M1,2020)  Monterey 12.6.1
- 2台でPleiades All in oneをクリーンインストール
- workspaceは新規作成

でダメでした
<img width="726" alt="skitch" src="https://user-images.githubusercontent.com/3235165/224459867-d282d656-22f1-43db-afd2-84146baa595f.png">

- 念のため設定 > サーバー > ランタイム環境からサーバーを削除し、新たなサーバーを作成しなおしましたが、状況は変わりませんでした

**Comment by cypher256** [comment]
/Applications/Eclipse_2022-12.app/Contents/Eclipse/eclipse.ini
-javaagent の行を削除して Pleiades 無しでも発生しますか？

**Comment by YukinobuYoshihara** [comment]
@cypher256 
ありがとうございます。
[pleiades-off.log](https://github.com/cypher256/pleiades.io/files/10947651/pleiades-off.log)
[pleiades-on.log](https://github.com/cypher256/pleiades.io/files/10947653/pleiades-on.log)

症状はかわりませんでした。 .logに気になるエラーが出ているのでpleiadesのon / off 時の両方のログをお送りします

**Comment by cypher256** [comment]
うーん。わからーん。

sh 起動で Tomcat Manager アクセスできるということで、関係なさそうですが、
このあたりのセキュリティソフトとか関係ないですよね。
https://qiita.com/mochimochix/items/ba4b5ff9ebea57ee55f9

Eclipse のヘルプメニューからマーケット・プレースは開けますか？ 
(関係なさそうですが、念の為、外部ネットワーク接続確認)

私の環境がまだ Intel 版 CPU なので確認できないこともあり、Pleiades All in One も Intel 版のままなので、
Mac ARM (Apple Silicon) CPU 上の Rosetta で動かした場合の、問題かもしれません。
Mac ARM 向けの Pleiades All in One のリリースは予定はしていますが、もう少し先になりそうです。

Pleiades 無しでも発生するということで、Pleiades 直接の問題ではなく、本家 Eclipse の問題か、
組み合わせの問題かもしれません。
