### ISSUE TITLE
https://pleiades.io/からPhpStormのドキュメントのリンクが英語マニュアルにredirectされる

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#13]
再現手順

1. https://pleiades.io/
2. PhpStormのリンクをクリック

3. https://www.jetbrains.com/help/phpstorm/meet-phpstorm.html に飛ぶ

期待値
PhpStormのリンクをクリックすると、日本語マニュアルが表示される

**Comment by cypher256** [comment]
**原因**
jetbrains.com で各ヘルプトップページに 302 リダイレクトが設定されており、それに対応して、
pleiades.io に付け替える処理を行っているが、それが今回に限り機能していない。原因不明。

**対応内容**
302 リダイレクトが nginx サーバキャッシュに有効期限 24 時間で残っているためクリアした。
ユーザ側もブラウザに 24 時間キャッシュが残るようになっているため、数時間以内に回復予定。
明示的にブラウザキャッシュをクリアすれば、すぐに回復可能。
（今回の対応がなくても、少なくとも 24 時間以内には回復はすると思われる）

**ワークアラウンド**
302 リダイレクトの location ヘッダの URL ドメイン部分を削除しているが、
暫定で削除後も http で始まる部分が残っていれば、削除して / から始まるパスに変換するようにした。

**Comment by mhorioka** [comment]
ありがとうございます。現在は問題ないことを確認しました。
今後JetBrains側で調査が必要なことがあればお知らせください。
