### ISSUE TITLE
誤記：インタープリタ表記の誤り

### ISSUE THREAD

**Issue by Yumihiki** [cypher256/pleiades.io#130]
いつもお世話になっています。

該当リンク
https://pleiades.io/help/idea/configuring-python-sdk.html#2c7548a5

- システムインタープリターを設定する
- 5. インタープリターフィールドに、必要なインタープリター実行可能ファイルへの完全修飾パスを入力するか、the Browse button をクリックして、開いた Java インタープリターを選択ダイアログで、目的の Java 実行可能ファイルを選択します。

正しくはPython SDKの項ですので 
- Python インタープリター
- Python 実行可能ファイル
と思われます。ご確認をお願いします。

**Comment by cypher256** [comment]
ご指摘、ありがとうございます。
JetBrains ヘルプサイトの英語原文誤りみたいなので、担当の方へ報告します。
https://www.jetbrains.com/help/idea/configuring-python-sdk.html#2c7548a5
@mhorioka

**Comment by mhorioka** [comment]
@cypher256 @Yumihiki フィードバックありがとうございます。

英語ドキュメントの問題は https://youtrack.jetbrains.com/issue/IDEA-316161/ に報告しました。

**Comment by Yumihiki** [comment]
YouTrackでの報告・対応の話になるのですね。
ご対応いただいてありがとうございます。
ちなみに、このような場合でも次からこちらのissueでも大丈夫なのでしょうか？
それとも、直接報告した方がお手間にならず好ましいでしょうか？

**Comment by cypher256** [comment]
@Yumihiki 
はい、JetBrains 英語ヘルプサイトの場合は JetBrains YouTrack に報告していただけると助かります。

**Comment by Yumihiki** [comment]
承知しました。今回はJetBrains英語ヘルプサイトの確認を失念していたので、そちらも併せてチェックの上、適切な方へ連絡出来るように努めますね。
ご確認とご対応ありがとうございました。
