### ISSUE TITLE
2023最新版　JavaScript エディタで構文の色などがつかない

### ISSUE THREAD

**Issue by rg-jp** [cypher256/pleiades.io#131]
2023リリース版をインストールしていろいろ試していますが、jsファイルを開くと、エディタ上で構文の色などがつきません。
右クリック　→　次で開く　で、いろいろなエディタを試してみましたが同じです。
Eclipse Web JavaScript 開発者ツールとか、インストールしてみたのですが、JavaScriptエディタのようなエディタが出てきません。
2012-12 版のときは、（少し見づらい色でしたが）構文の色が付いていたのですが。
何か解決方法はありますか？

インストールしたのは、2023リリース版の、Java Standard Edition です。Pydev を追加でインストールしました。
ワークスペースは2012-12版で使っていたディレクトリのコピー、新規に作成したワークスペースの両方で試しました。

**Comment by cypher256** [comment]
2022 から js ファイルは Wild Web Developer (WWD) というプラグインが標準になっています。
右クリックから「汎用テキスト・エディター」で開くと WWD が使用されます。

pleiades-2023-03-java-win-64bit_20230326.exe
で確認したところ、構文の色は正常に表示されました。
PyDev を入れると、色が表示されなくなりました。
PyDev が WWD に対応していないなどの問題かと思われます。

**Comment by rg-jp** [comment]
Pydev の影響でしたか。
そういえば、Pydev をインストールしたとき、「使えませんが、それでもインストールしますか？」みたいなメッセージが出ていたような。続行したら、使えたので気にしてませんでしたが。
Java とPython の両方で、並行して実装することも多く、Pydevはほしいので、js に関しては他の方法を模索してみます。
ありがとうございました。

**Comment by mktlab** [comment]
この件と関連するか分かりませんが私の環境では
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.wildwebdeveloper [502]
の例外が発生していて、おそらくそれが原因で色が付かない状況です。
確認すべき点などあれば教えていただけませんでしょうか。

[log.txt](https://github.com/cypher256/pleiades.io/files/11427122/log.txt)

![2023-05-09](https://user-images.githubusercontent.com/19543418/236991908-c8adc35f-7608-4628-a4c2-9ab0b32fe7a3.png)

**Comment by cypher256** [comment]
最初は発生しないみたいですが、更新か何かが走ると、この現象が発生し、
原因としては WWD と LSP4J がバージョン不整合になるようです。
前のコメントで PyDev を入れると書きましたが、更新が原因かもしれません。

workspace を退避して、インストールした後、起動する前に workspace フォルダを
戻すと問題が解消されることを確認しました。
(workspace も作り直す場合は、戻す必要はありません)

**Comment by rg-jp** [comment]
結局、いろいろ試してみて、WWD は諦め、JavaScript については、
JavaScript 開発ツール Chromium/V8 リモート・デバッガーを入れ、Chromium Debugging Editor で編集することにしました。
とりあえず色は付いてるので。

**Comment by mktlab** [comment]
> 最初は発生しないみたいですが、更新か何かが走ると、この現象が発生し、 原因としては WWD と LSP4J がバージョン不整合になるようです。 前のコメントで PyDev を入れると、と書きましたが、更新が原因かもしれません。
> 
> workspace を退避して、インストールした後、起動する前に workspace フォルダを 戻すと問題が解消されることを確認しました。 (workspace も作り直す場合は、戻す必要はありません)

上記対応で問題解消されること確認しました。
しかし、また3回くらいPleiadesを再起動するとエラー発生してしまう状況です。
Pleiadesの問題ではなくWWD、LSP4Jの問題なのですかね・・・

**Comment by cypher256** [comment]
WWD、LSP4J の問題と思われるため、本チケットとしてはクローズします。

**Comment by mktlab** [comment]
Pleiades 2023-06.20230617 では本件発生しないことを確認しました。
