### ISSUE TITLE
プロジェクトの共有Gitで「プラグイン "org.eclipse.ui.workbench" からのコードの起動で問題が発生しました。」が発生

### ISSUE THREAD

**Issue by elliotli02** [cypher256/pleiades.io#133]
下記の操作でエラーが発生しています。
チーム->プロジェクトの共有（Git）->完了後

エラー内容：
プラグイン "org.eclipse.ui.workbench" からのコードの起動で問題が発生しました。

例外：
java.lang.LinkageError: loader constraint violation: when resolving method 'org.eclipse.jgit.lib.Repository org.eclipse.egit.core.RepositoryCache.getRepository(java.io.File)' the class loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @690a0350 of the current class, org/eclipse/egit/gitflow/ui/internal/properties/RepositoryPropertyTester, and the class loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @51689ee9 for the method's defining class, org/eclipse/egit/core/RepositoryCache, have different Class objects for the type org/eclipse/jgit/lib/Repository used in the signature (org.eclipse.egit.gitflow.ui.internal.properties.RepositoryPropertyTester is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @690a0350, parent loader 'platform'; org.eclipse.egit.core.RepositoryCache is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @51689ee9, parent loader 'platform')

セッション・データ
eclipse.buildId=4.27.0.20230309-1200
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=ja_JP
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

This is a continuation of log file C:\pleiades202303\workspace\.metadata\.bak_0.log
Created Time: 2023-04-13 17:31:13.300

**Comment by cypher256** [comment]
古いクラスキャッシュが残っているように見えます。
eclipse.exe -clean.cmd
で起動してみてください。（最近 -clean はかなり時間がかかるようになりました。）

**Comment by elliotli02** [comment]
上記のコマンドで解決しました。
ご対応いただき、ありがとうございます。
