### ISSUE TITLE
XAMPPのPHP８対応版更新について

### ISSUE THREAD

**Issue by Levanira** [cypher256/pleiades.io#134]
現在pleiadesで採用しているXAMPPのPHPバージョンは7.4.33となっていますが、PHP7.X系は昨年の１１月で公式のサポートが終了となっています。
XAMPPを最新のPHP８対応バージョンのものに更新する予定はありますでしょうか？

**Comment by cypher256** [comment]
現在 Eclipse PDT が PHP 8 対応進行中っぽいので、それが正式リリースされれば対応したいと思っています。
https://github.com/eclipse/pdt/issues/148

**Comment by Levanira** [comment]
素早いご回答ありがとうございます。
内容承知いたしました。

**Comment by cypher256** [comment]
PDT の 8.2 対応はまだみたいなので、8.1 で Pleiades All in One 2023-06 をリリースしました。
XAMPP は 8.1.17 です。

＃ここに 8.2 の更新サイトリンクがあるけど 404
https://github.com/eclipse-pdt/pdt/releases/tag/R8_0_0

**Comment by cypher256** [comment]
プロジェクト作成時に普通に 8.2 選べますね。
次回リリースに同梱する XAMPP 8.2 にする予定です。

**Comment by cypher256** [comment]
PHP 8.2 版リリース済みのためクローズ
