### ISSUE TITLE
Gradleプロジェクト表示されなくなった

### ISSUE THREAD

**Issue by seven530** [cypher256/pleiades.io#137]
Pleiades All in One Eclipseをいつも愛用しております。
2023-06.20230617のバージョンにて、
Gradlrプロジェクトがえらーなしインポートしましたが、プロジェクトエクスプローラーにて表示されなくなった。
2023-03.20230326のバージョンではプロジェクトエクスプローラーにて表示されます。
ご確認とご対応のほど、宜しくお願い致します。

**Comment by cypher256** [comment]
バージョン: pleiades-2023-06-java-win-64bit-jre_20230617.exe
いくつかの Gradle プロジェクトをインポートしてみましたが、正しくインポートできるようです。
パッケージ・エクスプローラーに表示されていませんか？
以下、試してみてください。

* インポート > 一般 > フォルダーまたはアーカイブからプロジェクト
* インポート > 一般 > 既存プロジェクトをワークスペースへ
* インポート > Gradle > 既存の Gradle プロジェクト

**Comment by seven530** [comment]
承知致しました。試してみます。
お騒がせして申し訳ありません。
イシューをクローズ致します。

**Comment by seven530** [comment]
ご連絡ありがとうございます。

承知致しました。試してみます。
お騒がせして申し訳ありません。
イシューをクローズ致します。
________________________________
差出人: Shinji Kashihara ***@***.***>
送信日時: 2023年6月22日 12:54
宛先: cypher256/pleiades.io ***@***.***>
CC: seven530 ***@***.***>; Author ***@***.***>
件名: Re: [cypher256/pleiades.io] Gradleプロジェクト表示されなくなった (Issue #137)


バージョン: pleiades-2023-06-java-win-64bit-jre_20230617.exe
いくつかの Gradle プロジェクトをインポートしてみましたが、正しくインポートできるようです。
パッケージ・エクスプローラーに表示されていませんか？
以下、試してみてください。

  *   インポート > 一般 > フォルダーまたはアーカイブからプロジェクト
  *   インポート > 一般 > 既存プロジェクトをワークスペースへ
  *   インポート > Gradle > 既存の Gradle プロジェクト
