### ISSUE TITLE
resources 配下のファイルが反映されない

### ISSUE THREAD

**Issue by hiroyuki-tobari** [cypher256/pleiades.io#138]
**バージョン**
pleiades-2023-06-java-win-64bit-jre_20230617

**事象**
Resources handling is broken when there is a .mvn folder #1150と同様の事象が再発しております。
resources配下のxmlファイルがjarファイルに反映されない。

**試したこと**
該当プロジェクトでmaven更新を個別に実施すると解消するが、正常に動作していた依存関係にある別のプロジェクトにて同事象が発生する。
2023-03バージョンに戻したところ、事象が解消した。

**Comment by cypher256** [comment]
プロジェクトのプロパティ > Java のビルド・パス > ソース・タブ > src/main/resources > 除外
** が設定されている場合は削除してみてください。
下記によると発生頻度は低いようですが、解消されていないようで、Pleiades 側では対処できなさそうです。
https://github.com/spring-projects/sts4/issues/929#issuecomment-1574063266

一応 m2e の最新スナップショット版は下記からインストール可能です。
ヘルプ > 新規ソフトウェアのインストール 
M2E - Eclipse 用 Maven 統合
https://download.eclipse.org/technology/m2e/snapshots/latest/

**Comment by cypher256** [comment]
修正版が 2023/09 リリースに含まれそうです。
https://github.com/eclipse-m2e/m2e-core/issues/1302

**Comment by cypher256** [comment]
次のリリースでいくつかのパターンで解消されていることと、
Pleiades の問題ではないため、本チケットとしてはクローズします。

**Comment by hiroyuki-tobari** [comment]
ご連絡遅れました。
情報提供ありがとうございました。
2023/09 リリースで改善されていました。
