### ISSUE TITLE
Eclipse マーケットプレースからMyBatis Generator 1.4.2 をインストールできない

### ISSUE THREAD

**Issue by yzbh007** [cypher256/pleiades.io#139]
エラー・ログ：
https://mybatis.jfrog.io/artifactory/generator-eclipse-release/ のリポジトリーを読み取ることができません。
https://mybatis.jfrog.io/artifactory/generator-eclipse-release/ は有効なリポジトリー・ロケーションではありません。

**Comment by cypher256** [comment]
配置先の jfrog.com の無料利用枠が無くなったとか表示されてますね。
zip からインストールできるかと思います。

1. https://github.com/mybatis/generator/releases から、org.mybatis.generator.eclipse.site-~~~.zip をダウンロード
2. 下記みたいにインストール
https://qiita.com/AkihikoOgata/items/bb22250e3096aa558170#3%E8%BF%BD%E5%8A%A0%E3%82%A2%E3%83%BC%E3%82%AB%E3%82%A4%E3%83%96%E3%81%A7%E3%83%80%E3%82%A6%E3%83%B3%E3%83%AD%E3%83%BC%E3%83%89%E3%81%97%E3%81%9Fzip%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E9%81%B8%E6%8A%9E

**Comment by cypher256** [comment]
更新サイトの問題と思われるため、本チケットとしてはクローズします。
