### ISSUE TITLE
[要望] C++の規格解説サイトを日本語版へのリンクにしてほしい

### ISSUE THREAD

**Issue by cmplstofB** [cypher256/pleiades.io#14]
**件のページ** [`https://pleiades.io/help/clion/cpp_support.html`](https://pleiades.io/help/clion/cpp_support.html)

**要望**
記事「[C++規格準拠](https://pleiades.io/help/clion/cpp_support.html)」において，各C++規格を解説する外部サイトが英語版へのリンクになっていますが，日本語版へのリンクに変更してほしいです。
例えば文字リテラルについての解説ページへのリンクは，現状「[<code>https://<b>en</b>.cppreference.com/w/cpp/language/character_literal</code>](https://en.cppreference.com/w/cpp/language/character_literal)」というURLですが，「[<code>https://<b>ja</b>.cppreference.com/w/cpp/language/character_literal</code>](https://ja.cppreference.com/w/cpp/language/character_literal)」というURLの，同じ内容が日本語で記述されたページがありますので，そちらにリンクするようにして頂けると嬉しいです。

**Comment by cypher256** [comment]
以下、対応しました。

* サイト全体で以下のリンク先 URL 置換ルールを設定
(.+//)en(.cppreference.com) → $1ja$2
いくつかリンク先の ja 版が未作成のページがありますが、誰かが作成することを期待
* 該当ページの翻訳をいくつか修正

**Comment by cmplstofB** [comment]
ありがとうございます！
