### ISSUE TITLE
PhpStorm: Rector が 学長 と翻訳されている

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#140]
対象：

https://pleiades.io/help/phpstorm/rector.html

オリジナル（英語）
https://www.jetbrains.com/help/phpstorm/rector.html

Rector
https://github.com/rectorphp

提案：

Rector は訳さずに英語のまま

**Comment by cypher256** [comment]
ありがとうございます。Rector は訳さないようにしました。

https://pleiades.io/help/phpstorm/rector.html
https://pleiades.io/help/phpstorm/run-configuration-rector.html
https://pleiades.io/help/idea/run-configuration-rector.html
https://pleiades.io/help/idea/rector.html

上記以外のページはサーバ側のキャッシュが消えてから反映される予定です。

**Comment by mhorioka** [comment]
ありがとうございます！
