### ISSUE TITLE
Zend Studio13.6（Ecxlipse4.6.3）の日本語化ができず、起動できない

### ISSUE THREAD

**Issue by jyoisamu** [cypher256/pleiades.io#141]
日本語化の Pleiades プラグインは無事インストール完了したが、起動はできませんでした。
Java SE DK 20をインストールして同じでした。

Pleiades プラグイン
https://mergedoc.osdn.jp/pleiades-redirect/pleiades-win.zip.html

ZendStudio.iniに下記レコードが存在することが確認済み
     -Xverify:none
     -javaagent:～/pleiades.jar

そもそも、ZendStudioに使えないですか。

**Comment by cypher256** [comment]
Java 8 みたいですね。最新版は Java 11 未満に未対応のため、
Pleiades プラグインダウンロードボタンの下の下記リンクからダウンロードしてください。
アーカイブ: Java 8 対応版はこちら

**Comment by jyoisamu** [comment]
アドバイスありがとうございます。

公式サイトに公開したJAVA８のWINDOWS版をインストールしましたが、
INIファイルに下記レコードが入っていなかったため、手動で追加しましたが、最新版のと同じ現象で起動できませんでした。

-Xverify:none
-javaagent:dropins/MergeDoc/eclipse/plugins/jp.sourceforge.mergedoc.pleiades/pleiades.jar


やはり無理でしょうか。

**Comment by cypher256** [comment]
インストーラで ini ファイルが更新できていない場合、下記も最新版のままかもしれません。
dropins/MergeDoc/eclipse/plugins/jp.sourceforge.mergedoc.pleiades/pleiades.jar
こちらでは下記のように日本語化できてるみたいです。

Windows 11 Pro
ZendStudio-13.6.1-win32.win32.x86_64.exe
pleiades-win_20210507.zip

![image](https://github.com/cypher256/pleiades.io/assets/1156871/2c571a42-5241-4dab-ac13-95f621254f4c)

**Comment by jyoisamu** [comment]
-javaagent:C:/Program Files/Zend/Zend Studio 13.6.1/dropins/MergeDoc/eclipse/plugins/jp.sourceforge.mergedoc.pleiades/pleiades.jar

上記のように変更して起動できました。
デフォルトの相対パスではこちらの環境ではうまく見つけないみたいです。

**Comment by cypher256** [comment]
Windows のショートカットの場合、作業フォルダが exe と同じ場所である必要があります。

**Comment by cypher256** [comment]
... -clean.cmd で起動してみてください。
