### ISSUE TITLE
https://mergedoc.osdn.jp/  が証明書エラー開けません

### ISSUE THREAD

**Issue by tomakatuya** [cypher256/pleiades.io#142]
<img width="368" alt="image" src="https://github.com/cypher256/pleiades.io/assets/65111361/16007898-3e33-4098-9b1b-13531348d44d">

証明書のエラーで開けません。
どのようにダウンロードすればよろしいでしょうか。

**Comment by cypher256** [comment]
詳細設定 -> ftp.jaist.ac.jp にアクセスする リンクをクリックするか、
ブラウザの URL を https から http に変更して、ダウンロードしてください。

**Comment by cypher256** [comment]
現在は解消していると思われるためクローズ
