### ISSUE TITLE
PyCharm: フォーマッタ名 "Black" が「黒」と訳されている

### ISSUE THREAD

**Issue by kanra824** [cypher256/pleiades.io#143]
"Black"というフォーマッタ名が「黒」と訳されている箇所があります。Black のままのほうが適切かと思われます。

日本語版
https://pleiades.io/help/pycharm/reformat-and-rearrange-code.html#format-python-code-with-black

英語版
https://www.jetbrains.com/help/pycharm/reformat-and-rearrange-code.html#format-python-code-with-black

**Comment by cypher256** [comment]
ありがとうございます。対応しました。
ブラウザ強制リロードで反映されるかと思います。

**Comment by cypher256** [comment]
対応済みのためクローズ
