### ISSUE TITLE
eclipse2023(Python Windows 64bit版)にて、プロジェクトのsrcフォルダがPYTHONPATHに含まれない

### ISSUE THREAD

**Issue by hana2sei** [cypher256/pleiades.io#144]
プロジェクトのsrcフォルダがPYTHONPATHに含まれていないため、モジュール内で定義した関数を別モジュールで呼び出そうとするとエラーが発生します。
エラー例：ModuleNotFoundError: No module named 'test'

プロジェクトの設定をみると、srcフォルダは自動的にPYTHONPATHに含まれると書かれているのでバグではないかと思います。
![参考](https://github.com/cypher256/pleiades.io/assets/84162551/5ca82bc6-fa44-41b0-8e45-0ceeb48a1997)

（他のバージョンでも検証しましたが、eclipse2022では同様の不具合が発生し、eclipse2021では発生しませんでした）

**Comment by cypher256** [comment]
プロジェクト作成時、下記が選択されていますか？
![image](https://github.com/cypher256/pleiades.io/assets/1156871/b2b6b072-4b36-4e36-a152-6b46532824f4)

**Comment by hana2sei** [comment]
はい、「srcフォルダを作成してPYTHONPATHに追加する」にチェックを入れて作成しています。
参考のため、実際のソースコードとプロジェクト構成、実行結果が確認できるキャプチャを準備しましたのでご参考になれば幸いです。
![参考](https://github.com/cypher256/pleiades.io/assets/84162551/0e64f61c-f9fe-4524-99d6-a2c8989e9a91)

また、管理者様と私の環境で差異が考えられる部分を素人考えではありますが推測してみました。ご参考になれば。
①eclipseとは別に、Python3.10.8がインストールされている。（※１）
②Windows版である

（※１）
![参考２](https://github.com/cypher256/pleiades.io/assets/84162551/182db284-a6a2-44e4-808f-38b24eb745c4)

**Comment by cypher256** [comment]
具体的な再現手順ありがとうございます。
ご指摘いただいた 2021 版で問題ないとのことを踏まえ確認したところ、
2022 以降の付属 python 3 のパッケージングに問題がありました。

- 2021 以前
Windows installer (64-bit)
- 2022 以降
Windows embeddable package (64-bit)

python インストーラー版を元にパッケージングしなおしてリリースしたいと思います。

**Comment by hana2sei** [comment]
ご確認ありがとうございます。
お手数おかけいたしますが、ご対応よろしくお願い致します。

**Comment by cypher256** [comment]
対応してリリースしました。
https://mergedoc.osdn.jp/index.html#/pleiades_distros2023.html

2023-09.20231005
・更新: Gradle プロジェクト雛形の gradle wrapper 8.3 -> 8.4
・更新: #144 Python 3: Windows embeddable package (64-bit) -> Windows installer (64-bit)

**Comment by hana2sei** [comment]
ありがとうございます。
早速ダウンロードさせていただき、動作することを確認できました。
