### ISSUE TITLE
Standard Editionが開けない。

### ISSUE THREAD

**Issue by Hamada-local** [cypher256/pleiades.io#145]
2023－09において、Java Full Versionはダウンロードーダブルクリックによる起動が正常に行えインストール出来ます。しかし、Standard Editionは、ダウンロードは出来ますが、ダブルクリックしても起動しません。こちらの環境のせいかもしれませんが・・・
何が悪いのか調べる手立てはないでしょうか。
環境は、
　　　　Windows10、全ての更新を行い最新状態
　　　　Javaは21
です。

**Comment by cypher256** [comment]
Eclipse 本体ではなく、その前のダウンロードした自己解凍 exe ファイルの実行ですよね。

こちらではダブルクリックで解凍できるようです。
Pleiades All in One Java  Standard Edition
pleiades-2023-09-java-win-64bit_20231005.exe
Windows 11 Pro

### ファイル名と サイズ
<img width="438" alt="image" src="https://github.com/cypher256/pleiades.io/assets/1156871/05138984-8490-49c4-aefc-9036945b2901">

### コマンドプロンプトからダウンロードした自己解凍書庫の MD5 を確認
```
Z:\Downloads>certutil -hashfile pleiades-2023-09-java-win-64bit_20231005.exe md5
0e3ed4cdd2c017d234f5bfd870ff7540
```
![image](https://github.com/cypher256/pleiades.io/assets/1156871/1886452b-fbd1-4591-a17b-1035db8ce9cd)
<img width="569" alt="image" src="https://github.com/cypher256/pleiades.io/assets/1156871/02849112-ee40-4955-82b5-d2fb95c98ba5">

###  他、以下も試してみてください。

- 7-Zip や WinRAR をインストールしていれば、ダウンロードした exe ファイルを
エクスプローラー右クリックから解凍したり、解凍前に中身を確認できます。
- コマンドで解凍先を指定して解凍できます。
pleiades-2023-09～.exe -s2 -dc:\pleiades\2023-09

**Comment by Hamada-local** [comment]
MD5の内容はOKです。
コマンドで解凍先を指定すると実行できました。エクスプローラのダブルクリックだと駄目なようです。
アーカイバは現在使用していないので解凍前の確認は出来ていません。

**Comment by Hamada-local** [comment]
試しにExplzhをインストールしてみました。
エクスプローラの右クリックー即時解凍で実行できました･
結局、エクスプローラのダブルクリックによる実行のみ駄目でした。
私の環境、WIndows10に何かあるんですかね。取り敢えず実害はないのですが・・・

**Comment by cypher256** [comment]
現状試せる Windows 10 環境がないので、Windows 10 での動作は確認できていません。
自己解凍書庫 exe ファイル作成やビルドは macOS 上で行っているので、
ビルドプロセス自体には Windows バージョン依存の関連は無さそうです。
ひとまず、この Issue はオープンなままにしておきます。

**Comment by Hamada-local** [comment]
いろいろ試しています。
ファイル名を～.zipに変えてExplzhで解凍を指示したら正常に実行されました。
Windows本体を何かしたのかな？？

**Comment by Hamada-local** [comment]
突然ですが、旨く実行で来るようになりました。
Windowsの10月アップデートを行ったら、ダブルクリックでDefenderの警告は出ますが
実行を要求すると回答できました。
なにか、環境をおかしくしていたか、おかしかったようです。

**Comment by cypher256** [comment]
検証ありがとうございます。
Windows のセキュリティ関連の何かだったのかもしれませんね。
本件としては、ダブルクリックで解凍できたということでクローズします。
