### ISSUE TITLE
Eclipse Pleiades 2023 動的webプロジェクト実行できない

### ISSUE THREAD

**Issue by Kenta-kenpy** [cypher256/pleiades.io#146]
![A](https://github.com/cypher256/pleiades.io/assets/101815272/085f7911-0cb8-4f02-bf2b-89e492df628f)
![B](https://github.com/cypher256/pleiades.io/assets/101815272/9a0d6e2f-622b-44f7-aa5d-f9c9191d75a1)
・Eclipse　動的webプロジェクト実行できない
・HTMLやJSP&サーブレットの実行で外部プログラムでChromeを選べない

これまでJava文法的な学習をしていてパッケージエクスプローラを利用していた
最近になりサーブレット&JSPの学習のためプロジェクトエクスプローラを利用することになった
以前は2020を利用していたがせっかくならと最新版を入れてみた　そこで以下の現象に遭遇した

1．ツールバーの実行ボタンからサーバーで実行が消えた　実行の構成、お気に入りの編成しか選べない
2.パッケージの表示がフォルダになっている
3.プロジェクトエクスプローラで動的webプロジェクトの表示が?マークがついている

**Comment by cypher256** [comment]
2021 以降、以下が変更されています。
参考：『スッキリServlet 第3版』の改訂点＆ポイント！
https://sukkiri.jp/news/sukkiri_servlet3_changelog.html

> 1．ツールバーの実行ボタンからサーバーで実行が消えた　実行の構成、お気に入りの編成しか選べない

プロジェクト右クリ > 実行 > サーバーで実行 から実行するようになりました。
2 回目以降はサーバー・ビューから実行可能です。

> 2.パッケージの表示がフォルダになっている

ナビゲーター・ビュー廃止により、プロジェクト・エクスプローラーは素のディレクトリ構造を表示するようになりました。
以前に表示にするには、
プロジェクト・エクスプローラー右上の︙ > フィルターおよびカスタマイズ > コンテンツタブ
の全部あるいは必要なものをチェックしてください。

> 3.プロジェクトエクスプローラで動的webプロジェクトの表示が?マークがついている

svn や git などソース管理の設定ファイルが含まれていて、ソース管理サーバーに接続していない場合は
? が表示されます。

**Comment by Kenta-kenpy** [comment]
ありがとうございます

**Comment by Kenta-kenpy** [comment]
プロジェクト右クリックしても> 実行 > サーバーで実行が選べません
実行のところに実行の構成しか出てこない

普通のJavaプロジェクト(サーブレットJSPでないもの)についても実行できません

**Comment by cypher256** [comment]
パッケージ・エクスプローラーで開いたときに、以下のような表示になっていない場合、
正しい動的 Web プロジェクトになっていません。
![image](https://github.com/cypher256/pleiades.io/assets/1156871/79256c2f-43dd-435b-8435-e1d22e0f2243)

以下で新規プロジェクトを作成して、確認してみてください。
https://sukkiri.jp/books/sukkiri_servlet3/sukkiri_servlet3_appendix/create_dwp.html#:~:text=%E3%80%8C%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%80%8D%E3%83%A1%E3%83%8B%E3%83%A5%E3%83%BC%E2%86%92%E3%80%8C%E6%96%B0%E8%A6%8F,%E5%AE%8C%E4%BA%86%E3%80%8D%E3%82%92%E3%82%AF%E3%83%AA%E3%83%83%E3%82%AF%E3%81%97%E3%81%BE%E3%81%99%E3%80%82

**Comment by Kenta-kenpy** [comment]
正しい動的webプロジェクトじゃなかったってことなんですね
ファイルは前のフォルダというかそこからコピペで移せばいいでしょうか？

**Comment by cypher256** [comment]
はい、大丈夫だと思います。

**Comment by cypher256** [comment]
多量のマルチポストがあるようなので、クローズさせていただきます。
