### ISSUE TITLE
StandardエディションのPHPのプロジェクト･エクスプローラの表示がおかしい

### ISSUE THREAD

**Issue by Hamada-local** [cypher256/pleiades.io#147]
Pleiadesの問題では無いかもしれませんが・・・
StandardエディションのPHPを解凍インストールし、起動し既存のプロジェクトを開くと
プロジェクト･エクスプローラの表示内容が
　　　L/プロジェクト名/ディレクトリ名/ファイル名
となります。同じStandardエディションのJavaでは、ファイル名、のみが正しく表示され
ます。これまで使っていたEclipse版ではこのようなことはなかったんですが・・・・
何か、どこかに設定が必要なんでしょうか。

**Comment by cypher256** [comment]
プロジェクト・エクスプローラー > フィルターおよびカスタマイズ > コンテンツ >
Zip アーカイブ のチェックをはずしてみてください。
![image](https://github.com/cypher256/pleiades.io/assets/1156871/35f1e194-bd92-464f-b19a-a072e0ba1e4a)

この機能の現在のデフォルトは OFF ですが、2021 版などで ON になっている時期がありました。
また、その頃の ON になっているワークスペースを読み込むと、この問題が発生するのかもしれません。

**Comment by Hamada-local** [comment]
有り難うございました。無事かいしょうしました。
