### ISSUE TITLE
Eclipse 2018-12 へのリンクがない

### ISSUE THREAD

**Issue by 00A238** [cypher256/pleiades.io#15]
Pleiades All-in-One の[ダウンロードページ](http://mergedoc.osdn.jp/)から "Eclipse 2018-12" へのリンクが消えています。

**Comment by cypher256** [comment]
1 年に対して 1 バージョンを基本に過去バージョンリンクを残す予定にしています。
以下のいずれかをお使いください。
* Eclipse 2019-03
* Eclipse 2018-09

**Comment by 00A238** [comment]
了解しました，その更新ポリシーはどこかに明示されていますでしょうか。今後も「１年に対して（最新の）１バージョン（のみを残していく）」方針であれば，その旨をダウンロードページに書いておく方がいいと思います。
