### ISSUE TITLE
DBViwerはどのバージョンにあるか

### ISSUE THREAD

**Issue by Kenta-kenpy** [cypher256/pleiades.io#151]
研修でDBViewerプラグインを使うことに
しかし自宅でも練習しようと2020辺りをインストールしましたが見当たりません
しかもなぜか画面が英語になっています

**Comment by cypher256** [comment]
DBViwer は Pleiades All in One 4.8 まで含まれています。
* 2018 以降では SQL エディターが動作しなくなるなどの不具合が発生するようになったため、削除されました。
* DBViwer の最終更新は 2010 年で、保守されていません。

インストール方法は下記などを参照してみてください。
Qiita: 【Eclipse】DBViewerのインストール
https://qiita.com/nkojima/items/2a865b819071e7943761
