### ISSUE TITLE
誤訳:リストのツールチップ参照

### ISSUE THREAD

**Issue by shirayuki** [cypher256/pleiades.io#153]
お世話になっております。
使っていて違和感がありましたので誤訳かと思い報告します。
確認をお願いします。

> see\ tooltip\ for\ a\ list=リストのツールチップ参照

**Comment by cypher256** [comment]
ご指摘ありがとうございます。下記のように修正しました。
次回リリース時に反映します。

修正前: リストのツールチップ参照
修正後: リストはツールチップを参照

**Comment by cypher256** [comment]
Pleiades All in One 2023-12.20231211 でリリース済みのためクローズします。
