### ISSUE TITLE
ftp.jaist.ac.jpにアクセス出来ない

### ISSUE THREAD

**Issue by Yutaka-Tsubakiyama** [cypher256/pleiades.io#155]
サイトにアクセス出来ず、ダウンロードが出来ない

このサイトにアクセスできません
ftp.jaist.ac.jp からの応答時間が長すぎます。

Preparing to download Eclipse Pleiades All in One
https://ftp.jaist.ac.jp/pub/mergedoc/pleiades/2023/pleiades-2023-09-java-win-64bit-jre_20231103.exe
SIZE: 1160932911 bytes
MD5: c88d972bb39a8b47fc67eb871e20df85

**Comment by Yutaka-Tsubakiyama** [comment]
コメントありがとうございます。しばらくの間、待って見ます。

**Comment by Yutaka-Tsubakiyama** [comment]
先程、無事にダウンロード出来ました（2023.12.06 14:00）

**Comment by cypher256** [comment]
たくさん待っていただいたようで、
現在、JAIST の帯域を mergedoc (Pleiades) がたいぶ使ってるようです。

![image](https://github.com/cypher256/pleiades.io/assets/1156871/7138858e-722c-4bd4-ad2c-6ca7e4b13d23)
https://ftp.jaist.ac.jp/
