### ISSUE TITLE
内部エラーが発生しました: "追加情報の計算" Could not initialize class lombok.launch.PatchFixesHider$Javadoc

### ISSUE THREAD

**Issue by MuranakaTakiya** [cypher256/pleiades.io#156]
2024.2.15に2023版のpleiadesをインストールしました。（Lombok version: 1.18.31）
入力保管（Ctr＋Space）を実施したときに以下のエラーが発生しました。
<img width="289" alt="内部エラー" src="https://github.com/cypher256/pleiades.io/assets/115383722/1fbf81c7-4934-40a8-9478-53b79429ebab">

Lombok公式サイトより、最新バージョン（Lombok version: 1.18.30）をインストールしなおしたところ、解消はされました。
https://projectlombok.org/download

現時点（2023.12以降）のpleiadesをインストールすると、当事象が発生すると思いますのでご確認させて頂きました。

**Comment by cypher256** [comment]
解消方法ありがとうございます。
以下をリリースしました。

2023-12.20240218
・更新: #156 Lombok 1.18.31 (Edge) -> 1.18.30 に差し戻し

**Comment by MuranakaTakiya** [comment]
早々のご対応ありがとうございました！
