### ISSUE TITLE
Eclipseアップデート後、Windows Defenderに関するエラーが発生

### ISSUE THREAD

**Issue by Riopika** [cypher256/pleiades.io#157]
Eclipseアップデート後、起動時に毎回添付のエラーメッセージが表示されます。
原因をご教示ください。
なお、Windows Defender はTrend Microのウイルスバスターをインストールしているので無効化してあります。
![WindowsDefenderError](https://github.com/cypher256/pleiades.io/assets/60454400/f26651e9-9642-4759-b22a-a3e0c66e194e)

**Comment by cypher256** [comment]
本家でも Windows Defender 未使用時の問題として報告されているようです。
https://bugs.eclipse.org/bugs/show_bug.cgi?id=582994

**Comment by cypher256** [comment]
Eclipse 2024-03 から Windows Defender の起動時チェックを
スキップできるようになるため、これで解消できるかもしれません。

![image](https://github.com/cypher256/pleiades.io/assets/1156871/567d7088-7697-43e1-8b5c-8e5f52b80b2e)

**Comment by Riopika** [comment]
上記設定を行ったところ、エラーが出なくなりました。
ありがとうございました。
