### ISSUE TITLE
Eclipse php issue "colon expected"

### ISSUE THREAD

**Issue by riok1280** [cypher256/pleiades.io#158]
Recently, I have updated eclipse php from 2020-12 to 2023-12 and have encountered an unexpected error as follows.

![Image2](https://github.com/cypher256/pleiades.io/assets/163272223/c2592246-06fe-437a-8ac5-5af248b12fda)

You can read the error message is "colon expected". It is apparenetly misleading.
Strange is that if you change the file extension of the html file from ".html" to ".HTML", the error is disappeared.

If there is any setup method to restore this phenomenon , please advise.

**Comment by cypher256** [comment]
Workaround: Disable the HTML Language Server.

![image](https://github.com/cypher256/pleiades.io/assets/1156871/6ddedda8-82f1-4e4d-8ab6-363ddf451d7c)

**Comment by riok1280** [comment]
Thanks a lot for your advice. It worked fine.
