### ISSUE TITLE
ウィザードにスプリングブートが存在しない

### ISSUE THREAD

**Issue by YD11213120** [cypher256/pleiades.io#159]
私はultimateのeclipseをダウンロードしたのですがウィザードにスプリングブートが表示されないのです。
eclipse Marketでspring toolがダウンロードされているのは確認したのですが…

**Comment by cypher256** [comment]
2024 Ultimate で確認したところ、こちらの環境では問題ないようです。

### Windows 11 - pleiades-2024-03-ultimate-win-64bit-jre_20240325.exe
<img width="849" alt="image" src="https://github.com/cypher256/pleiades.io/assets/1156871/474043c9-b1be-4078-884b-d9b4aef2a263">

### macOS Sonoma - pleiades-2024-03-ultimate-mac-jre_20240325.dmg
<img width="799" alt="image" src="https://github.com/cypher256/pleiades.io/assets/1156871/2a25b669-36f0-4fb8-848b-a334adb1dfa6">

**Comment by cypher256** [comment]
メニュー > ファイル > 新規 > プロジェクト...  から進んだ場合
Windows 11 - pleiades-2024-03-java-win-64bit-jre_20240325.exe

<img width="500px" src="https://github.com/cypher256/pleiades.io/assets/1156871/d511778c-2fb0-4b38-8bd1-f7bcd7fad7d1">
