### ISSUE TITLE
broken layout.

### ISSUE THREAD

**Issue by k-brahma** [cypher256/pleiades.io#16]
base document:
https://www.jetbrains.com/help/pycharm/debugging-django-template-tutorial.html

for section below:

Type the following code:

from django.shortcuts import render

def index(request):
    return render(request, 'index.html', context={'hello': 'world'})
    

You see that index.html is marked as unresolved reference:

**Comment by cypher256** [comment]
Fixed translation engine to output source code block as it is.
https://pleiades.io/help/pycharm/debugging-django-template-tutorial.html
