### ISSUE TITLE
2024-06のダウンロードで404エラーとなる

### ISSUE THREAD

**Issue by yomogist** [cypher256/pleiades.io#162]
- 以下のURLからのダウンロードで404エラーとなるようです。
https://ftp.jaist.ac.jp/pub/mergedoc/pleiades/2024/pleiades-2024-06-java-win-64bit-jre_20240617.exe

**Comment by cypher256** [comment]
現在、JAIST ミラーサーバの管理者の方に問い合わせています。

速度が遅いですが、ダウンロードページの右上の「ミラー・サーバーの選択」で
pleiades.io
を選択し、ダウンロードボタンを押して表示された URL をコピーして、
ダウンロードできます。https でない警告が出ますが無視して続行してください。

**Comment by yomogist** [comment]
ワークアラウンドのご提示ありがとうございます。
ただ残念ながらプロキシなどの都合によりHTTPでのダウンロードができない環境におります。
jaistの復旧を待ちたいと思います。
よろしくお願いいたします。

**Comment by yomogist** [comment]
本日10:45分頃に試してみたところ、正常にダウンロードできました。
ありがとうございました。
