### ISSUE TITLE
SonarLint plugin 追加要望

### ISSUE THREAD

**Issue by nwtks** [cypher256/pleiades.io#163]
Pleiades All in OnePleiades All in Oneの付属プラグインにSonarLintの追加は可能でしょうか。
https://www.sonarsource.com/products/sonarlint/features/eclipse/

**Comment by cypher256** [comment]
SonarLint 追加検討したいと思います。

参考: Eclipse Marketplace 30 日間ランキング
* 7位 SonarLint ★3264
* 21位 Checkstyle Plug-in ★1286
* 35位 SpotBugs Eclipse plugin ★956

削除プラグイン候補
* NTail

**Comment by cypher256** [comment]
SonarLint を[ワークスペース全体の設定のデフォルトとして無効にできず](https://stackoverflow.com/questions/48786932/disable-sonarlint-automatic-analysis-in-eclipse-by-default)（以下は可能）、大量にプロジェクトを開いているような既存ユーザーへの影響が大きすぎるため、プラグイン追加は見送りたいと思います。

* プロジェクト単位での無効化
* 設定の「ファイル除外」や「ルール構成」を使って無効化

代わり？に、SonarLint 設定画面の翻訳で足りてない部分が多かったので、Pleiades に翻訳を追加し、次回リリース予定です。
