### ISSUE TITLE
このソフトウェアの使い方の動画撮影について

### ISSUE THREAD

**Issue by yuki-snow-nieve-y** [cypher256/pleiades.io#164]
いつも、システムの開発などで統合開発環境エクリプスを愛用させて頂いております。

さて、この度は初学者を対象としたJavaの解説動画を撮影してYoutubeなどにアップしたいと考えております。
その際、学習環境構築として貴社のウェブサイトからエクリプスのダウンロード方法と
初期設定の方法を録画してアップする予定です。
その後も、エクリプス上でJavaのプログラミングを動作させるシーンが録画されます。

上記の動画を撮影しても問題無いでしょうか？
許可を頂ければ幸いです。

今後ともよろしくお願いいたします。

**Comment by cypher256** [comment]
ありがとうございます。
当プロジェクトとしては動画公開に関しまして問題ございません。

**Comment by yuki-snow-nieve-y** [comment]
早速のご返答ありがとうございます。
快諾して下さり感謝申し上げます。
