### ISSUE TITLE
RubyMine: Better method completion が メソッドの完成度の向上 

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#166]
Location:

日本語
https://pleiades.io/help/ruby/rbs.html#rbs_type_signatures

<img width="792" alt="image" src="https://github.com/user-attachments/assets/11004567-fba3-4885-b403-545214877e5e">

英語
https://www.jetbrains.com/help/ruby/rbs.html#rbs_type_signatures

Actual:

メソッドの完成度の向上

Suggestion:

メソッド補完の改善

or

より良いメソッド補完

**Comment by cypher256** [comment]
ご提案いただいた「メソッド補完の改善」としました。
その他、全体的に同様の箇所を見直し、対応しました。

**Comment by mhorioka** [comment]
ありがとうございます！
