### ISSUE TITLE
暗黙的スーパー・コンストラクター Object() は、デフォルト・コンストラクターについては未定義です。明示的コンストラクターを定義する必要があります

### ISSUE THREAD

**Issue by tigodgr** [cypher256/pleiades.io#167]
暗黙のスーパー・コンストラクター Object() は、デフォルト・コンストラクターについては未定義です。明示的なコンストラクターを定義する必要があります
というエラーが起こる。

**Comment by cypher256** [comment]
これは、Eclipse Java プロジェクトでの JRE 構成に関する一般的な問題です。

プロジェクトを右クリック > ビルド・パス > ビルド・パスの構成 > ライブラリー・タブ
JRE システム・ライブラリーをダブルクリックし、
代替 JRE に適切な JDK を設定してください。

また、インストール済みの JRE... を押して、
正しく設定されているか確認し、無い場合は、
JDK をインストールしてください。

Pleiades All in One Java Full エディションの場合は、
あらかじめ複数の JDK が設定されています。設定されていない場合は、
配置場所に問題があるか、移動したなど、環境に問題がある可能性があります。
