### ISSUE TITLE
Java タイプ・インジケーターについて

### ISSUE THREAD

**Issue by TheCocoa0x0** [cypher256/pleiades.io#168]
Javaのタイプ・インジケーターにチェックをつけてもファイルアイコンが付きません。

**Comment by cypher256** [comment]
Java タイプ・インジケーターのチェック OFF
![image](https://github.com/user-attachments/assets/e1051c1b-548c-46af-a5d4-09dac38e3102)

Java タイプ・インジケーターのチェック ON
![image](https://github.com/user-attachments/assets/75d277eb-ef37-43e4-bd99-59ff5e6313f8)

パッケージ・エクスプローラーの表示を確認したところ、機能しているようです。
プロジェクト・エクスプローラーなどではアイコンは表示されません。

**Comment by TheCocoa0x0** [comment]
確認をしてみたところ、プロジェクト・エクスプローラーを開いていたため表示されていませんでした。
パッケージ・エクスプローラーを確認してみたところ、無事表示され解決しました。
ありがとうございました！
