### ISSUE TITLE
PyCharm - Nose testsが鼻検査と訳されている

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#17]
問題箇所

https://pleiades.io/help/pycharm/run-debug-configuration-nose-test.html
このダイアログボックスを使用して、鼻検査(英語)の実行/デバッグ構成を作成します。
https://www.jetbrains.com/help/pycharm/run-debug-configuration-nose-test.html
Use this dialog box to create a run/debug configuration for Nose tests.

訂正案
Nose testsのままかNosetests （Python詳しくないですが、nosetestsというコマンドがあるみたいです）

**Comment by cypher256** [comment]
nose がテストフレームワーク名のようなので、下記で統一しました。
* Nose tests → Nose テスト
* Nosetest 、nosetests はそのまま

類似ページ
https://pleiades.io/help/idea/run-debug-configuration-nose-test.html

その他の修正
Expert=専門家 → エキスパート

**Comment by mhorioka** [comment]
ありがとうございます。確認ですが、

Nosetest 、nosetests はそのまま

というのは訳す、訳さないのどちらでしょうか？

現状ですと「Nose テスト」 と訳されているようにみえます。

例えば https://pleiades.io/help/idea/run-debug-configuration-nose-test.html　の見出し等

ぱっと見今のコンテキストだと訳しても良いように思えますが、 nosetests をコマンドとして使っている例はマニュアル上は無いように見えるので、どちらでもよいと思いますが、念の為確認した次第です。

**Comment by cypher256** [comment]
>「Nosetest 、nosetests はそのまま」
>というのは訳す、訳さないのどちらでしょうか？

ありがとうございます。訳さない想定でしたが、
データベースの登録が誤っていましたため、修正しました。

https://pleiades.io/help/pycharm/run-debug-configuration-nose-test.html
https://pleiades.io/help/idea/run-debug-configuration-nose-test.html

**Comment by mhorioka** [comment]
ご確認ありがとうございます。
