### ISSUE TITLE
Delete Problemsが削除の問題と翻訳されている

### ISSUE THREAD

**Issue by shirayuki** [cypher256/pleiades.io#18]
お世話になります。
(1)Delete Problemsが「削除の問題」と翻訳されていますが「問題の削除」だと思います。
　(「削除の問題」の意味で使用される箇所が他にあるのでしょうか?)
(2)×ビルド・ァイル⇒○ビルド・ファイル の誤字があります。

> Delete\ Problems=削除の問題
> Formats\ Ant\ buildfiles=Ant ビルド・ァイルのフォーマット

**Comment by cypher256** [comment]
2012年ごろに Eclipse Babel から取り込んだ訳に問題がありました。
ご指摘のとおり、以下に修正しました。次回リリース分に反映されます。

Delete\ Problems=問題の削除
Formats\ Ant\ buildfiles=Ant ビルドファイルのフォーマット

**Comment by shirayuki** [comment]
迅速な対応ありがとうございました。
もう一つ書かせてください。
リファクタリングの実行中に「Java 個の一致を検出」が表示されるのが気になります。
こちらも修正をご検討ください。

> Locating\ {0}\ matches={0} 個の一致を検出

**Comment by cypher256** [comment]
こちらも Babel からの取り込み分に問題がありました。
以下に修正しました。次回リリース分に反映されます。
> Locating\ {0}\ matches...={0} の一致を検索中...
