### ISSUE TITLE
Resolve using Rightが権利を使って解決する

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#20]
Originally Reported at twitter:https://twitter.com/liberaldenial/status/1139120232943906816

URL:
https://pleiades.io/help/phpstorm/resolving-conflicts.html

中央ペインで競合を右クリックして、コンテキストからコマンドを使用することもできます。左を使用して解決するコマンドと権利を使って解決するコマンドは、一方からの変更を受け入れ、もう一方からの変更を無視するためのショートカットを提供します。

Actual:「権利を使って解決する」

Expected（の例）:「右を使用して解決する」

Note:直前の「左を使用して解決する」 と訳が対照になるようになっていると良いと思います。

**Comment by cypher256** [comment]
下記をコーパスに登録し、該当ページのキャッシュをクリアしました。

Resolve using Right=右を使用して解決する
Resolve using Left=左を使用して解決する

**Comment by mhorioka** [comment]
ありがとうございました。
