### ISSUE TITLE
Eclipse 2019-03 Java Full Editon で Thymeleaf の補完が効かない

### ISSUE THREAD

**Issue by shusuke-nakamura** [cypher256/pleiades.io#22]
Thymeleaf プロセッサー候補がありません。
上記が表示され、補完機能が効かない状態です。

何か解決策はありませんでしょうか？

**Comment by cypher256** [comment]
Pleiades ALl in One のデフォルトで指定されている Eclipse 実行用 java が 11 だと、
プロジェクト右クリ > Thymeleaf > Thymeleaf の追加
で有効化できないようです。

eclipse.ini の -vm で Java 8 を指定してみてください。
開発対象のプロジェクトは Java 11 でも可能です。

**Comment by CarlaX** [comment]
really thanks, i change the -vm to jdk8, and it works!!!

**Comment by cypher256** [comment]
#41 で対応済み
