### ISSUE TITLE
AppCode で、プロジェクトが実行できない

### ISSUE THREAD

**Issue by isc-mizumoto** [cypher256/pleiades.io#23]
AppCode にPleiadesをインストールしたところ、
以下のメッセージが表示され、プロジェクトが実行できませんでした。

'xxxxx'の実行中にエラーが発生しました: 
Product not found for target 'xxxxxxxx.app'

日本語化を外すと問題なく実行できます。

確認した環境１
OS: 10.14.5
AppCode: 2019.1.4
Pleiades: 2019.06.30 版

**Comment by cypher256** [comment]
以下で再現できませんでした。
プロジェクトの内容や設定が関連しているかもしれないため、
新規プロジェクトからの再現パターン、あるいは他の再現方法などは分かりますでしょうか？

AppCode > 新規プロジェクト > iOS Application 
- Augmented Reality App
- Single View App
- Tabbed App 

実行したシミュレータ
- iPhone X | iOS 12.2
- iPhone 5s | iOS 12.2

環境 (同じ)
- OS: 10.14.5
- AppCode: 2019.1.4
- Pleiades: 2019.06.30 版

**Comment by isc-mizumoto** [comment]
お世話になります。

今日改めて確認したら、昨日実行できなかったプロジェクトがすんなり動作しました。
Mac再起動が影響しているのかもしれません。

再現性がありましたら改めて報告させてください。
