### ISSUE TITLE
Pleiades All in One Eclipse 2019-06 ZIPファイルが解凍できない

### ISSUE THREAD

**Issue by split-n** [cypher256/pleiades.io#24]
Pleiades All in One Eclipse 2019-06 Java Full Edition (Windows 64bit) のzipアーカイブ
(pleiades-2019-06-java-win-64bit-jre_20190630.zip) について、  
Windows 10 Explorerの標準機能を使って閲覧・解凍をしようとすると、
「フォルダーを開くことができません。 圧縮(zip 形式) フォルダー ～ は無効です。」というエラーが発生し、開くことができません。

MD5により、ダウンロードしたファイルが破損していないことは確認しています。  
7-zipによる閲覧・解凍は問題なく行えます。  
Windows 10 Enterprise 1803、Windows 10 Pro 1809 にて同問題を確認しました。

**Comment by cypher256** [comment]
下記確認しました。
- ✕ Windows エクスプローラー
- ○ 7-Zip
- ○ WinRAR

発生するファイル
- pleiades-2019-06-java-win-64bit_20190630.zip
- pleiades-2019-06-java-win-64bit-jre_20190630.zip

ひとまず、下記に注意書きと、この Issue へのリンクを記載し、暫定対応とします。
http://mergedoc.osdn.jp/#pleiades.html#zip-notice

**Comment by cypher256** [comment]
STS プラグインが Windows のパス長さ制限 260 文字を常に超えてしまうことが分かりました。
> #35 Springのプロパティエディタ/YAMLエディタでコンテンツアシストが効かない

トップページ、ダウンロードページに
Windows の zip 解凍は 7-Zip 必須の記述を赤字で追加しました。
（有償の WinRAR はひとまず記載無しにしました）

**Comment by osippoyo** [comment]
７-ZIPでもSTSプラグインの部分が解凍時にLIVEと名前の入っているファイルにエラーが出てうまく起動できません。

**Comment by cypher256** [comment]
#40 に記載します。
