### ISSUE TITLE
Pleiades All in One Eclipse 2019-06 Java11とJava12のJavadocの内容が日本語化されません

### ISSUE THREAD

**Issue by ghost** [cypher256/pleiades.io#25]
Pleiades All in One Eclipse 2019-06 Java Full Edition (Windows 64bit)にて
Java11とJava12のJavadocの内容が日本語化されません。
Javaエディタ内で表示させるホバーとJavadocビュータブの両方が英語表記になっています。
なおJava6～Java8は日本語化されており、設定から編集できるJavadocロケーションパスは日本語サイトとなっていました。
AdoptOpenJDKであることが原因でしょうか？解決方法のご教示、宜しくお願い致します。

**Comment by cypher256** [comment]
Eclipse 本体の不具合のように見えるので eclipse.org にバグ報告しました。
https://bugs.eclipse.org/bugs/show_bug.cgi?id=549029

**Comment by cypher256** [comment]
Java 9 Jigsaw 以降の JDK で問題が発生していましたが
2020-12 から動作するようになったので、クローズします。

**Comment by cypher256** [comment]
メモ： 
Java 9 Jigsaw 以降、クラスの Javadoc コメントは日本語で表示されるが、
メソッドの Javadoc コメントが英語のまま。Eclipse 本体の問題が完全に解消されていない。
