### ISSUE TITLE
Plediaes All in One Eclipse 2019-06でGlassFish toolsプラグインからGrassFishサーバ起動でエラー発生

### ISSUE THREAD

**Issue by JustyLight** [cypher256/pleiades.io#26]
Plediaes All in One Eclipse 2019-06にGrassfish tools 1.0.1をインストールしてGrasFishサーバを起動すると、エラーが発生します。ログには以下のメッセージが出力されていました。
java.util.MissingResourceException: Can't find bundle for base name sun.util.logging.resources.logging, locale ja_JP
色々確認したところ、sun.util.logging.resources.logging見つからない状況です。Eclispseの起動オプションでVMをjre1.8.0_221に変更したところ、GrasFishサーバが正常に起動・停止できました。
AdoptOpenJDK に上記のリソースが含まれていないのが原因のようです。

**Comment by cypher256** [comment]
下記状況のため、ご指摘いただいたように Eclipse 起動オプション -vm で 
Java8 を指定するなどして回避しているようです。

Glassfish Tools リポジトリ： Eclipse に移管されてから更新されてない
https://git.eclipse.org/c/glassfish-tools/glassfish-tools.git/log/

Glassfish Tools のバグを受け付けていない
https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Glassfish-Tools&component=General

Glassfish の java.util.MissingResourceException: Can't find bundle for base name sun.util.logging.resources.logging
- https://github.com/payara/ecosystem-eclipse-plugin/issues/2
- https://issues.apache.org/jira/browse/NETBEANS-2201?src=confmacro
- https://netbeans.org/bugzilla/show_bug.cgi?id=271032
