### ISSUE TITLE
SVNで「前の状態と比較」ができない

### ISSUE THREAD

**Issue by makimaki32** [cypher256/pleiades.io#27]
SVNリポジトリーのヒストリーを選び、差異を見たいファイルの右クリックメニューから、
「前の状態と比較」を実行すると、
変更部分の差異を見る画面が表示されるはずなのですが、
同じ内容が表示されてしまうことがあります。

連続で実行していると何度目かに、正常に差異が表示されます。
自分なりに調査したのですが、以下が問題なのではないでしょうか。

正常に比較できた場合は、以下の一時フォルダが２つできます。
比較できなかった場合は、一時フォルダが１しかできていません。

workspace\.metadata\.plugins\org.eclipse.team.svn.core\.tmpXXXXXXXXX
(XXXXXXXXXは時間に依存していそうな数字)

実行速度が速すぎて、２つ目のフォルダパスが１つ目と同じになってしまい、
内容を上書きすることになるので、
比較結果が同じになってしまっているのでは？と思いました。

環境
Plediaes All in One Eclipse 2019-06 64bit
SVN クライアント:SVNKit 1.8.14 r10627(SVN 1.9.0 compatible,all platforms)

以上です、よろしくお願いします。

**Comment by cypher256** [comment]
下記でバグ報告されているようです。vote すると解決が早まるかもしれません。
https://bugs.eclipse.org/bugs/show_bug.cgi?id=516851
https://bugs.eclipse.org/bugs/show_bug.cgi?id=536042

**Comment by makimaki32** [comment]
ご回答ありがとうございます。
voteしてみます。
質問してよかったです。今後もよろしくお願いします。
