### ISSUE TITLE
Plediaes All in One Eclipse 2019-06にCheckStyleﾌﾟﾗｸﾞｲﾝが格納されていません

### ISSUE THREAD

**Issue by YosukeNishino** [cypher256/pleiades.io#28]
対象 : pleiades-2019-06-java-win-64bit_20190630.zip

dropins/CheckStyle配下に、CheckStyleではなくSpotBugs4系のプラグインが格納されています。
また、dropins/SpotBugsにはSpotBugs3系のプラグインが格納されています。
※ダウンロードページ上、SpotBugsは4.0.0が格納されることになっています。

上記より、CheckStyleが初期状態で有効になっていません。
ご対応可能でしょうか。

**Comment by cypher256** [comment]
詳細ありがとうございます。修正して下記リリースしました。
本日中にミラーにも反映される予定です。

2019-06.20190810
・[github#28] CheckStyle プラグイン格納もれ対応
・Pleiades 更新

**Comment by YosukeNishino** [comment]
ご対応ありがとうございます。
以下確認致しました。

対象 : pleiades-2019-06-java-win-64bit_20190810.zip
* pleiades-2019-06-java-win-64bit_20190810.zip がミラーまで反映されていること。
* CheckStyleプラグインが格納されていること。また、Eclipse上で有効になっていること。
* CheckStyleプラグインが8.18.0であること（ダウンロードページ表記通り）。
* SpotBugsプラグインが格納されていること。また、Eclipse上で有効になっていること。
* SpotBugsプラグインが4.0.0であること（ダウンロードページ表記通り）。

残タスク無しとして、当issueはクローズさせていただきます。
今後ともよろしくお願い致します。
