### ISSUE TITLE
最新版でphpStormを日本語化後にgit操作をするとバージョン管理ウィンドウ内に"コンソール"タブが増殖

### ISSUE THREAD

**Issue by soony1st** [cypher256/pleiades.io#29]
最新版のPlediaes(2019-8-10版)でphpStorm(2019.2版)を日本語化後に、
phpStorm上からgit操作をすると、"バージョン管理"ウィンドウ内に
"コンソール"タブが無駄に増殖してしまうようです。

わりと以前から起こっていて、これまでは古いバージョン（2018年中頃）
のものを使うことでこの現象を避けていましたが、
古いバージョンのセットアップファイルを紛失してしまい、
対応方法がないかと投稿した次第です。

Plediaesのインストールはpleiades-win\setup.exeを実行して行いました。

ご見解いただけますと幸いです。

**Comment by cypher256** [comment]
コンソールタブの文字列で判定が行われているようなので、対応しました。
http://download.pleiades.io/download/pleiades/build/stable/pleiades-win.zip

2019.08.18
・[github#19] 最新版でphpStormを日本語化後にgit操作をするとバージョン管理ウィンドウ内に"コンソール"タブが増殖
・[Eclipse] 訳追加修正: Eclipse
・[IDEA] 訳追加修正: IntelliJ, Android Studio, TeamCity

**Comment by soony1st** [comment]
無事、修正されたことが確認できました。
迅速なご対応ありがとうございます。
