### ISSUE TITLE
Command Line Interfaceが「できます」と翻訳されている

### ISSUE THREAD

**Issue by shirayuki** [cypher256/pleiades.io#30]
お世話になっております。
ソフトウェア名の「Java implementation of Git - Command Line Interface」が、「Git Java 実装 - できます」と翻訳されています。
他の翻訳に影響がなければ修正してください。
よろしくお願いします。

> command\ line\ interface=できます

**Comment by cypher256** [comment]
ご指摘いただいた箇所を修正しました。
次回リリース分に反映されます。
