### ISSUE TITLE
「Refreshing Unity Assets」が「さわやかなUnityアセット」

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#31]
問題
- URL
（日本語）https://pleiades.io/help/rider/Refreshing_Unity_Assets.html
（英語）https://www.jetbrains.com/help/rider/Refreshing_Unity_Assets.html
の
- 見出しおよび左側のメニューで「Refreshing Unity Assets」が「さわやかなUnityアセット」
となっている

提案
-「Refreshing Unity Assets」を「Unityアセットの更新」と訳す

理由
-他の箇所で「auto-refresh」は「自動更新」と訳されているので辻褄があいそう

**Comment by cypher256** [comment]
IDE に適用する Pleiades では Update と区別するために、以下ルールがあります。
* Update → 更新
* Refresh → リフレッシュ

pleiades.io 全体でも上記を踏襲し、その他下記としました。
* Assets=資産 → リフレッシュ

本ページ以外は 24 時間以内に上記ルールが反映されます。

**Comment by mhorioka** [comment]
ありがとうございます！
