### ISSUE TITLE
日本語化するとGitHubの連携が正常にできない

### ISSUE THREAD

**Issue by sourcecordblue** [cypher256/pleiades.io#32]
GitHubアカウントの連携設定をしても、環境設定画面を閉じて開き直すと「Missing Access Token」になります。
日本語化すると別クライアント扱いになり、正常に連携できないのが原因のようです

**Comment by cypher256** [comment]
> 日本語化すると

いったん vmoptions の Pleiades 指定行を # でコメントアウトして
日本語化解除してみてください。

macOS Mojave 環境で色々確認したところ、日本語化していなくても、
複数の GitHub アカウントが指定できるようになった IntelliJ IDEA 2018.2 あたりから、
この現象が発生するようです。

**Comment by sourcecordblue** [comment]
日本語化を解除しても一度でも日本語化していると別アプリ扱いになるようで連携が正常には行われなくなってしまうようです・・・
再インストールし、英語のままで設定すると連携可能になるのですが、その後日本語化するとやはり切れてしまうようです。

**Comment by cypher256** [comment]
> 日本語化を解除しても一度でも日本語化していると

ありがとうございます。そのご指摘により切り分けできました。
数時間後に配布サイトに反映される予定です。

**原因**
アプリ名メニュー部分 ("IntelliJ IDEA" 配下) は Pleiades ではなく、macOS が参照するアプリ内の plist ファイルの言語設定により日本語表記となるように、Pleiades 起動時に plist の値を "English" を "Japanese" に書き換えていましたが、GitHub 連携機能が、その影響を受けてしまうようです。

**対応**
"IntelliJ IDEA" メニュー配下が英語のままになりますが、他の回避方法が分かるまで、この Pleiades 起動時の plist 書き換えを廃止します。なお、一度でも日本語化している場合は、下記に示すように手動で plist を元に戻す必要があります。

**再インストール方法**
1. Pleiades 2019.09.15 をダウンロードし、setup.app で再インストール
1. app 右クリ > パッケージの内容を表示 > Contents/Info.plist をエディタで開く > key CFBundleDevelopmentRegion の値 (6 行目あたり) を Japanese から English に戻す
1. IntelliJ 起動
