### ISSUE TITLE
Windows Java13環境でPleiadesがクラッシュする

### ISSUE THREAD

**Issue by Hamada-local** [cypher256/pleiades.io#33]
Windows10、Java13の環境でEclipse-PlatformにPleiadesを加えるとクラッシュする。
Eclipse-PlatformのみであればOK。
Java環境をJava12として起動するとOK。そして、終了した後、Java環境をJava13として起動するとOK。
なぜだろう？

**Comment by cypher256** [comment]
手元の環境では、以下で起動できました。
Windows 10
AdoptOpenJDK: OpenJDK13U-jdk_x64_windows_hotspot_13_33
Eclipse IDE for Enterprise Java Developers ベース

なお、Eclipse の起動 JRE を変更した場合は、
-clean 起動、または
configuration\jp.sourceforge.mergedoc.pleiades を削除して起動してください。
(ロードして AOP したクラスをキャッシュしているため)

なお、Pleiades では、
Eclipse 自体を実行する Java のバージョンとしては LTS (Java 11, 17 など) を
対象にサポートしたいと考えています。

**Comment by Hamada-local** [comment]
コメント有り難うございました。
改めて確かめてみました。
新たに作成したEclipse+Pleiadesを対象に
1.Oracle　Java13では、エラー発生し起動できない。
2.OpenJDK　Java13では、起動できる。
さらに、この後OracleーJava13に戻しても起動できました。
Pleoadesが正常に起動できる環境で一度起動できたら、その後はOracle　Java13で使えるようですね。
Java12とJava13の違いがどうなのか分かりませんが、All in Oneを使わずに、Pleiadesを利用する立場で
申しますと宜しくない結果ですね。

**Comment by Hamada-local** [comment]
何故か問題の再発が無くなりました。
どうも、OpenJDKを一度動かしたことが影響しているのではないかと思います。OpenJDKを使用する前は
キチンと毎回再発していました。
どういう理由かは分かりませんが、原因不明なままです。
