### ISSUE TITLE
IntelliJを日本語化するとJAVA FXプラグインが使用不可能になる[バグ報告]

### ISSUE THREAD

**Issue by storchP** [cypher256/pleiades.io#37]
初めまして。現在IntelliJ IDEA Community Edition 2019.2.4(64bit)を使用しています。
マニュアルに沿って日本語化ツールpleiades-2019.10.03を適用させた所、今まで使えていたIntelliJ IDEAのJAVA FXプラグインの表示が使用不可となってしまい、ビルド出来ていたJAVA FXプロジェクトもビルドできなくなってしまいました。
これは日本語化ツールの元々の仕様で止むを得ないのでしょうか？
或いは、設定方法やバージョンの指定如何で回避出来る、一種のバグでしょうか？
どうぞご教示下さいませ。

**Comment by cypher256** [comment]
同じバージョンで試したところ、新規 fx プロジェクトは作成できました。
プラグインの表示でボタンに「使用不可」と出ている場合は使用可能な状態です。
以下を試してみてください。

- ファイル > キャッシュの破棄 / 再起動
- プロジェクトのインポートをし直す
