### ISSUE TITLE
Pleiades プラグイン 2019.10.03 Android Studio 3.5.2でコード補完の際不必要なスペースが表示されている

### ISSUE THREAD

**Issue by SorrowBlue** [cypher256/pleiades.io#38]
windows 10 1909
Pleiades プラグイン 2019.10.03

通常の補完が見切れている
![通常の補完が見切れている](https://user-images.githubusercontent.com/25735189/69834409-80d6e380-127d-11ea-8fd8-b2b8bd21792b.png)

Ctrl + Spaceで表示をした際は見切れません
![Ctrl + Spaceで表示をした際は見切れません](https://user-images.githubusercontent.com/25735189/69834433-a8c64700-127d-11ea-9cee-9dd7a4d158f1.png)

古いバージョンの公開場所はありますか？

**Comment by cypher256** [comment]
英語文字列を日本語文字列にして短くなったときに IndexOutOfBoundsException が
発生するのを抑止するために、空白を追加する対応に問題があったため修正しました。
数時間後以降にダウンロード可能になります。

リリース Version 2019.11.29
