### ISSUE TITLE
apt_generatedが正常に生成できません。

### ISSUE THREAD

**Issue by deconding** [cypher256/pleiades.io#39]
Pleiades 2019-06、2019-09この二つバージョンに、両方とも同じ問題があります。

DOMAを利用してapt_generatedを生成したい場合、以下のようなエラーを出ています。

> 構文エラーがあります。"enum Identifier" を挿入して EnumHeader を完了してください
> 構文エラーがあります。"EnumBody" を挿入して EnumDeclaration を完了してください

生成したImplファイルを確認すると、以下のようになっています。
`package com.test;
`
`/** */
`
`@org.springframework.stereotype.Component()
`

eclipse.orgからダウンロードした「eclipse-jee-2019-09-R-win32-x86_64.zip」で確認しました。
こちらで問題がありません。

ご確認の程宜しくお願い致します。

**Comment by cypher256** [comment]
再現できていないのですが、以下を確認してみてください。

Spring Boot/Doma/トラブル
http://yakinikunotare.boo.jp/orebase2/java/spring/spring_boot/doma/trouble

[Spring Boot] MySQL5.7+Doma2の組み込み
https://trans-it.net/spring-boot-mysql5-7doma2/

Pleiades All in One 2019-06 や 2019-09 は Java 11 で起動しています。
11 以外で起動する場合は、eclipse.ini の -vm を指定してください。

**Comment by deconding** [comment]
cypher256さん

-VMを指定して確かに正常にビルドできました。
大変ありがとうございました。

一点わからないですが、
Eclipseの設定→JAVA→インストール済みJREのところに、java8を指定してもなぜビルドできませんか？

**Comment by cypher256** [comment]
現状の Eclipse APT は、Eclipse を起動した JRE 上で動いているためです。
Eclipse ワークスペースのデフォルト設定や、プロジェクト設定は参照されていません。
本来なら、これらで設定した Java のバージョンで処理されるべきかとは思います。

**Comment by deconding** [comment]
大変助かりました。
誠にありがとうございました。
