### ISSUE TITLE
「Null Safety」が「安全性がない」と翻訳されている

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#4]
場所：
https://pleiades.io/intellij/sdk/docs/tutorials/kotlin.html

問題：
「Null Safety」が「安全性がない」と翻訳されている

提案：
「Null安全」または「null安全」

**Comment by cypher256** [comment]
対応：
「Null Safety」を「null 安全」となるように辞書追加。（要リロード）

追加対応：
* Kotlin が翻訳禁止ワードにも関わらず、コトリンとなってしまっている処理を修正
* 同ページに以下の問題があったため、翻訳禁止ワードに gradle を追加
(Gradle は元から翻訳禁止ワードだったが先頭小文字も対象として追加)
> Kotlinを使ってグラデルスクリプトを書く
> グラデーション4.4の後、グラデーションは

**Comment by mhorioka** [comment]
ありがとうございます。確認しました。
