### ISSUE TITLE
アップデートを適応すると起動できなくなる

### ISSUE THREAD

**Issue by osippoyo** [cypher256/pleiades.io#40]
Windows10で7-ZIPを使い展開した際、ヘッダーエラーと言う表記とそれとは別にエラーが出るファイルがあり恐らくそのせいでアップデートが正常に適応されません。
確認をお願いします

**Comment by cypher256** [comment]
以下で解凍エラーや起動エラーは発生しませんでした。

- pleiades-2019-09-java-win-64bit-jre_20191007.zip
- Windows 10 Professional  1909
- 7-Zip 19.00 (2019-02-21) 64bit MSI

他、以下を試してみてください。
- 上書きインストールしない
- ドライブ直下にインストール (空白や日本語が含まれないディレクトリ)
Program Files や ダウンロード、デスクトップは避ける
- -clean 起動する

**Comment by osippoyo** [comment]
すべて試しましたがエラーが出て正常に起動しませんでした追記ですがインストールしたのはアルティメットエディションです。


     ----- Original Message -----

**Comment by cypher256** [comment]
Ultimate でも問題は発生しませんでした。以下の情報を教えて下さい。

- 7-Zip のバージョンとインストールタイプ (msi, exe ？)
- 解凍した zip ファイル名
- 解凍した具体的な操作、解凍後の eclipse.exe のパス
- 解凍時のエラーの詳細
- Eclipse 起動時のエラー詳細

**Comment by osippoyo** [comment]
現状わかる範囲ですmsipleiades-2018-09-ultimate-win-64bit-jre_20181004右クリックで展開を選択・7zipからファイルを開いて展開Windows１０は一般向けの方です
     ----- Original Message -----

**Comment by osippoyo** [comment]
展開時はヘッダーエラーとliveと名前のついたファイルがエラーになります起動時にThe Edipse executable launcher was unable to locate its companion libraryの表示が出ます

     ----- Original Message -----

**Comment by cypher256** [comment]
解凍後のディレクトリ配置は下記のように、短いパスになっていますか？
d:\pleiades\eclipse\eclipse.exe

**Comment by osippoyo** [comment]
はい。プレアデスフォルダはC直下にありますエグゼの配置も下の例とほぼ同じ構図です

     ----- Original Message -----

**Comment by osippoyo** [comment]
再送です。解凍先はC直下なので短いです


     ----- Original Message -----

**Comment by cypher256** [comment]
WinRAR で解凍してみてください。
（有償ですが体験版が使用できます）

**Comment by osippoyo** [comment]
問題なく解凍できました。ありがとうございます

     ----- Original Message -----
