### ISSUE TITLE
コロンの両隣にスペースを入れると動かない

### ISSUE THREAD

**Issue by CleanDiesel** [cypher256/pleiades.io#42]
[JetBrains 製品の日本語化マニュアル](https://pleiades.io/pages/pleiades_jetbrains_manual.html)に
```
-Xverify:none
-javaagent:(構成ディレクトリのフルパス)/jp.sourceforge.mergedoc.pleiades/pleiades.jar
```
のように書いてありますがコロンの両隣にスペースを入れてしまうと動かないので注意書きしたほうがいい。

**Comment by cypher256** [comment]
確認したところ、マニュアルの記載にスペースは含まれていないようです。
