### ISSUE TITLE
【不具合】DBのカラム名まで日本語化されてしまう

### ISSUE THREAD

**Issue by sadachi** [cypher256/pleiades.io#43]
pleiades Windows最新版(2019-12-25) + PHPStorm 2019.3.1

データベースツールにてカラム名まで日本語化されてしまう
※PHPStorm2018.3では発生していませんでした

**Comment by sadachi** [comment]
![shot_200129_161042](https://user-images.githubusercontent.com/4263329/73335465-d26a1180-42b2-11ea-96cb-c81ab3872c36.png)

**Comment by sadachi** [comment]
❌カテゴリー　使用可能　作成しました
🔴category enable created

**Comment by cypher256** [comment]
テーブル表示部分の作りが変更されていて除外されなくなっていました。
対応してコミットしたので、数時間後にはダウンロード可能になります。

Pleiades バージョン 2020.01.29

**Comment by sadachi** [comment]
ありがとうございます！正しく表示されることを確認できました。
確認・返答が遅くなり申し訳ありません。
