### ISSUE TITLE
XDocletエラー

### ISSUE THREAD

**Issue by Riopika** [cypher256/pleiades.io#44]
Eclipse 2019-12のWindows 64bit Java Full Editionを使用していますが
以下のエラーが発生しています。
『ライブラリーがありません: xdoclet-1.2.3.jar. XDoclet のホーム・ディレクトリーを選択してください。 1.2.3』

それらしいプラグインも入っていないため、解決策をご教示下さい。
![Xdoclet_Error](https://user-images.githubusercontent.com/60454400/73411507-fed06d00-4348-11ea-9a55-25bdde2878e5.jpg)

**Comment by cypher256** [comment]
XDoclet を使用していない場合は動作に支障はないため無視してください。
使用している場合は、下記を設定してください。
https://stackoverflow.com/questions/27737968/why-this-eclipse-error-showing-and-what-should-be-the-solution-for-it

**Comment by Riopika** [comment]
教えていただいたサイトを参考にjarファイルをEclipseのプラグインフォルダに入れたところ、
警告メッセージが消えました。
ありがとうございました。
