### ISSUE TITLE
C/C++プロジェクトを作成する項目が見つからない。

### ISSUE THREAD

**Issue by tubame135** [cypher256/pleiades.io#45]
先日、プログラミングを始めたいと思ってEclipse 2019/12のPleiades all in one C/C++のFull Editionをダウンロードし、インストール、起動しました。しかし、C/C++プロジェクトを作成する項目がないどころかJavaの開発環境のみ構成されているように見えました。(慣れない目で見ているので本当にそうかがわからないです)
つまるところ、C/C++の開発環境を構成することができていなかったんだと思います。何かしらの操作が誤っている、もしくは足りていないのでしょうか。
使用OSはMacOSX Catalina 10.15.2です。

**Comment by cypher256** [comment]
ビルドの構成に失敗していました。
数時間後にリリースします。
