### ISSUE TITLE
死んだ.NETコード/dead .NET code

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#46]
https://pleiades.io/help/resharper/Find_dead_code.html

死んだ.NETコード　の「死んだ」は見るとびっくりするのでカタカナで「デッド」のほうが望ましいと思われます。

死んだ　で検索すると「死んだオブジェクト」というのもあるようです。これも「デッド」のほうがよいのではと個人的には思います。

https://pleiades.io/help/dotmemory/Comparison_View.html

**Comment by cypher256** [comment]
後フィルタで下記を適用するようにしました。
死んだ → デッド
(IntelliJ Pleiades ではデッドと訳していました)

ご指摘の 2 ページはキャッシュを消し、反映済みです。
その他のページはキャッシュが 1 日残るため 1 日以内に反映されます。

**Comment by mhorioka** [comment]
ありがとうございます。
