### ISSUE TITLE
IntelliJのエディション誤訳

### ISSUE THREAD

**Issue by mirror-kt** [cypher256/pleiades.io#47]
https://pleiades.io/help/clion/develop-plugins-for-clion.html

`IntelliJ IDEA コミュニティまたは究極エディション`となっていますが、
`IntelliJ IDEA CommunityまたはUltimateエディション`とするのが適切ではないでしょうか。

**Comment by cypher256** [comment]
修正しました。
全体の類似部分も確認し、同じように対応しました。
