### ISSUE TITLE
リダイレクトが複数回行われる

### ISSUE THREAD

**Issue by mirror-kt** [cypher256/pleiades.io#48]
https://pleiades.io/intellij/sdk/docs/reference_guide/api_changes_list.html

![image](https://user-images.githubusercontent.com/43880251/76091714-71e09980-6001-11ea-8477-56ae4d1bf785.png)

**Comment by cypher256** [comment]
オリジナルの英語サイトが SSLv3 に対応しなくなったことにより、問題が発生していたため、
対応しました。以下のサイトが対象です。

https://pleiades.io/intellij/sdk/docs/intro/welcome.html
https://pleiades.io/help/resharper/sdk/README.html
