### ISSUE TITLE
Migu 1M フォントを使用していると空白文字が文字化けする

### ISSUE THREAD

**Issue by isc-mizumoto** [cypher256/pleiades.io#49]
Eclipse のエディタフォントを Migu 1M にして使用していますが、
2019-12 にアップデートしたところ、空白文字(改行やタブ文字)が文字化けします。
eclipse.ini から pleiades を外すと問題が発生しないので、pleiades の問題と思われます。

**Comment by cypher256** [comment]
以下の Windows、Mac で確認したところ、発生しませんでした。
All in One を新しく入れても発生しますか？

Eclipse
pleiades-2019-12-java-win-64bit-jre_20200213.zip
pleiades-2019-12-java-mac-jre_20200213.dmg

Migu 1M ダウンロード
https://mix-mplus-ipa.osdn.jp/migu/

**Comment by isc-mizumoto** [comment]
私の環境依存ということで、了解しました。
もう一度、環境を構築してみます。
ちなみに、使用しているパッケージは、Windows 64bit php standard です。
pleiades-2019-12-php-win-64bit_20200213.zip
Java とxampp を別途インストールしています。
