### ISSUE TITLE
sysroot がシロウトと翻訳されている

### ISSUE THREAD

**Issue by photom** [cypher256/pleiades.io#5]
https://pleiades.io/help/clion/remote-debug.html
リモート GDBデバッグ の  sysroot の項目の箇所です。
「sysroot」 のままでも良いように思いますがカタカナにするなら「シスルート」になるかなと思います。

**Comment by cypher256** [comment]
以下、対応しました。
- [Ss]ysroot を翻訳禁止ワードに追加
- target リモート' args → 'target remote' 引数
- 末尾が「もっと。」になる問題を修正
