### ISSUE TITLE
ReSharper C++のincludes Analysis周りの翻訳の調整

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#50]
対象ページ
https://www.jetbrains.com/help/resharper/Analyzing_Includes.html
https://pleiades.io/help/resharper/Analyzing_Includes.html

1)
ReSharper | Inspect | Analyze Includes in… 
ReSharper | インスペクション | 分析に含まれる...

Analyze Includes は 英語のままか、「Includeを解析」がよさそう

2) 
The Includes analysis window provides two separate views, Includees and Includers, 
分析を含むウィンドウには、2つのビューインクルードとインクルードがあります。ど

->(The) Includes analysis  は  英語のままか、「Include解析」が良さそう
-> Includee(s), Includer(s)は翻訳対象外としたほうが良さそう

3)
Times included 
時が含まれて

Line contribution shows 
ラインのコントリビュート

Line contribution inclusive is similar to Line contribution,
ライン貢献度はラインのコントリビュートに似ていますが

->Times included　は　英語のままか「include回数」がよさそう
->Line contribution や Line contribution inclusive  は英語のままがよさそう

**Comment by cypher256** [comment]
以下、ご指摘いただいたように訳を変更しました。
Analyze は基本的に「分析」としているため、合わせました。

Analyze Includes in…
修正前: 分析に含まれる...
修正後: include の分析...

Analyze Includes in Current Project
修正前: 現在のプロジェクトに分析を含める
修正後: 現在のプロジェクトの include を分析

Analyze Includes in Solution
修正前: ソリューションに含まれる分析
修正後: ソリューションの include を分析

Includes analysis
修正前: 分析を含む
修正後: include 分析

以下、ご指摘いただいたように、特殊ケースとして英語のままとしました。

Includees
修正前: インクルード
修正後: (英語のまま)

Includers
修正前: インクルード
修正後: (英語のまま)

Times included
修正前: 時が含まれて
修正後: (英語のまま)

Line contribution
修正前: ラインのコントリビュート
修正後: (英語のまま)

Line contribution inclusive
修正前: ライン貢献度
修正後: (英語のまま)

**Comment by mhorioka** [comment]
ありがとうございます🙇🏻‍♂️
