### ISSUE TITLE
【脱字】ドキュメント内での説明に脱字が存在する

### ISSUE THREAD

**Issue by morisakiryotanssol** [cypher256/pleiades.io#51]
対象ページ
https://pleiades.io/help/youtrack/standalone/Keyboard-Shortcuts.html

`Down Arrow`の説明欄

As is ：「現在の課題の課題にフォーカスを設定します。」
To be：「現在の課題の下の課題にフォーカスを設定します。」

些細ですが一応報告しておきます。
![スクリーンショット (5)](https://user-images.githubusercontent.com/44353677/76826720-8d00a400-6860-11ea-815a-b99f38654cc0.png)

**Comment by cypher256** [comment]
ご指摘部分に関して、翻訳後の最適化に問題があったため、
対応しました。
