### ISSUE TITLE
Twigが小枝と訳されている

### ISSUE THREAD

**Issue by NotWhiteButHundred** [cypher256/pleiades.io#53]
https://pleiades.io/help/phpstorm/symfony-templates.html
で、「Symfony プラグインは小枝特有のの機能も提供します。」は
「Symfony プラグインはTwig特有の機能も提供します。」ではないでしょうか？

**Comment by cypher256** [comment]
修正しました。
同じ誤訳が他に 3 ページあり、そちらはキャッシュが消え次第反映されます。

**Comment by NotWhiteButHundred** [comment]
素早い対応ありがとうございました！
