### ISSUE TITLE
Intellij IDEA2020.1が日本語化できません

### ISSUE THREAD

**Issue by maccadoo** [cypher256/pleiades.io#54]
Intellij IDEA2020.1が日本語化できません
おそらくidea64.vmoptionsやidea64.exe.vmoptionsの保存位置が変わっているのが原因だと思います。
Windows版もLinux版も日本語化不能です。mac版は確認していません。
Windows版はWindows10の1909で確認しています。
Linux版はubuntu18.04で確認しています。

Windows版
%userprofile%\\.IntelliJIdea2020.1\config
     ↓
%userprofile%\AppData\Roaming\JetBrains\IntelliJIdea2020.1

Linux
~\\.IntelliJIdea2020.1\config
     ↓
~\\.config\IntelliJIdea2020.1

日本語化で作成されるjp.sourceforge.mergedoc.pleiadesなどのディレクトリを新しいディレクトリに移してidea64.exe.vmoptionsを編集しパスを再設定すると今度は、Intellij IDEAのメニューが消えてしまいます。
ご確認お願い致します。

**Comment by mirror-kt** [comment]
macでの状況です.
macOS Catalina(10.15.4)において、IntelliJのスプラッシュスクリーンの表示までは確認できましたがその後ウィンドウが表示されることなく固まります。

よろしくお願いします。

**Comment by cypher256** [comment]
対応したものをアップロードしました。
http://download.pleiades.io/download/pleiades/build/stable/pleiades-win.zip
http://download.pleiades.io/download/pleiades/build/stable/pleiades-mac.zip

以下、今後対応予定です。
- vmoptions の保存位置変更対応 (インストーラの配置は以前のままですが動作すると思います)
- 以前、日本語になっていた部分が英語になっている部分がある。

**Comment by maccadoo** [comment]
ご対応ありがとうございます
無事日本語化されました

**Comment by mirror-kt** [comment]
macでの動作確認しました
対応ありがとうございます

**Comment by rtazaki** [comment]
Windows10 Pro 1909
ideaIC-2020.1.exe
pleiades-2020.04.11
の組み合わせで、いつもの通り
pleiades-win\setup.exeをたたき、
C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.1\bin
idea64.exe
を日本語化しようと試みましたが、うまく日本語化されませんでした。

PC依存の可能性があったため報告しませんでしたが、
同条件の別PCでも同じ現象となっているため、再度ご確認お願い致します。

**Comment by cypher256** [comment]
以下、パスの変更に対応しました。ご確認ください。

> Windows版
> %userprofile%\.IntelliJIdea2020.1\config
> ↓
> %userprofile%\AppData\Roaming\JetBrains\IntelliJIdea2020.1

2020.04.20
・[IDEA][github#54] 2020.1 の vmoptions 位置変更に関する Pleiades インストーラー対応

**Comment by rtazaki** [comment]
遅くに対応ありがとうございます。
無事日本語化されました。

**Comment by cypher256** [comment]
検索でこのページが上位に表示されるため追記

JetBraisn 公式日本語言語パックのインストール
https://pleiades.io/pages/pleiades_jetbrains_manual.html
