### ISSUE TITLE
サイトからpleiadesがダウンロードできない

### ISSUE THREAD

**Issue by kaja-html** [cypher256/pleiades.io#55]
https://mergedoc.osdn.jp/
からPleiades プラグイン・ダウンロードのWindows版をダウンロードしようとしました。
popUpは許可しましたが、さてダウンロードというときに画面遷移して白い画面のままずっと変わらないです。
chrome、firefox（共に最新バージョン）で確認しました。

**Comment by cypher256** [comment]
現在、高負荷になっているようです。
しばらく、待ってから試してみてください。

**Comment by kaja-html** [comment]
今できました、ありがとうございました！
