### ISSUE TITLE
SSHトンネルを使用したデータベース接続がエラーとなる

### ISSUE THREAD

**Issue by mikan-megane** [cypher256/pleiades.io#56]
データベースのSSH設定にてLocalPortを空のまま保存すると  
`SSH tunnel creation failed:. com.intellij.execution.ExecutionException: SSH: Requested local port is not an integer: <動的> `  
と出て接続エラーとなる

再度SSH設定ダイアログを開くとLocalPortに`<動的>`という文字が入っている。

Pleiadesを読み込まないようにし、LocalPortから`<動的>`という文字を削除すると接続が出来るようになるため`<Dynamic>`を翻訳する際のバグかと思われる。

**Comment by cypher256** [comment]
ご指摘部分の <Dynamic> や localhost を翻訳除外しましたので、ご確認ください。
http://download.pleiades.io/download/pleiades/build/stable/pleiades-win.zip
http://download.pleiades.io/download/pleiades/build/stable/pleiades-mac.zip

**Comment by mikan-megane** [comment]
翻訳が除外され、接続出来ることを確認しました。
素早いご対応ありがとうございます。
