### ISSUE TITLE
WARファイルにwork.*のようなパッケージのクラスファイルが格納されない

### ISSUE THREAD

**Issue by YT0014** [cypher256/pleiades.io#57]
Tomcat用のプロジェクトで、jp.**とwork.**の、２系統のパッケージ構成で開発を行っています。
このプロジェクトでWARファイルを作成した場合、WEB-INF/classes/に、work以下のファイル群が格納されず、jp以下のファイル群のみとなります。
これは、正常な挙動なのでしょうか？
もちろん、eclipse上では正常に動作し、クラスファイルも正常に作成されているのを確認しています。

なお、eclipseのバージョンは、以下の通りです。
Eclipse Java EE IDE for Web Developers.
Version: Mars.2 Release (4.5.2)
Build id: 20160218-0600

**Comment by cypher256** [comment]
Pleiades を無効化してみて確認してみてください。
現象が発生しないようであれば、Pleiades 側で対応を検討します。

**Comment by YT0014** [comment]
ご回答ありがとうございます。
質問後、ソースの解析ができ、Tomcat Manager Pluginの処理で、work以下のディレクトリを、格納対象から除外する処理を行っているのが確認できました。
最上位ディレクトリに作成される作業用ディレクトリのworkを除外する処理の副作用だと思われます。

Pleadesにおける問題でなかったことをお詫び申し上げます。
