### ISSUE TITLE
VerifyErrorが発生する

### ISSUE THREAD

**Issue by orihalcon128** [cypher256/pleiades.io#59]
eclipse.iniから「-Xverify:none」を削除するとVerifyErrorが発生します。
下記のリンクに書かれているように「StyledString」の「descriptor」を「String」から「Object」へ変更すると起動できるようになります。
https://forums.ubuntulinux.jp/viewtopic.php?pid=121053

**Comment by cypher256** [comment]
現象および、そのページ内容は何度か見ているのですが、
StyledString のコンストラクタの引数は String であり、元の内容が正しく、
Object に変更することにより、定義自体が無効となり、
エラーが発生しなくなっているのかと思われます。

後日確認し、対応を検討します。

**Comment by cypher256** [comment]
Pleiades 本体を単体リリースしました。
数時間後に反映されます。

2021.04.21

・[github#80] Checkstyleでエラーが発生する
・[github#79] Pull Resultの誤訳
・[github#59] VerifyErrorが発生する
・Java 要素ホバー時に表示される Java 14 以降の日本語 Javadoc URL 自動設定対応 (ワークスペース作成時)
・ダーク系テーマ Windows で問題ビューなどのヘッダー罫線、設定ダイアログの罫線を目立たなくする AOP 定義追加
・エディター上の印刷マージン線アルファを薄くなるように AOP 定義追加
・ニーモニック処理で ConcurrentModificationException が発生する問題を修正
・クイック・アクセスのダイアログの説明が翻訳されない場合の対応
・パッケージ・エクスプローラーでプロジェクトが Servers のみの場合、ビュー内に新規メニューを表示
・訳追加修正: Eclipse, PDT, STS, Subclipse, WindowBuilder, Batch Editor

**Comment by orihalcon128** [comment]
エラーが発生します。
```
java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    org/eclipse/jface/action/MenuManager.<init>(Ljava/lang/String;Ljava/lang/String;)V @1: invokevirtual
  Reason:
    Type uninitializedThis (current frame, stack[0]) is not assignable to 'java/lang/Object'
  Current Frame:
    bci: @1
    flags: { flagThisUninit }
    locals: { uninitializedThis, 'java/lang/String', 'java/lang/String' }
    stack: { uninitializedThis }
  Bytecode:
    0000000: 2ab6 0237 b602 3c13 023e b601 c09a 0009
    0000010: 2b01 b802 444c 2a2b 012c b701 ecb1     
  Stackmap Table:
    full_frame(@22,{Object[#230],Object[#215],Object[#215]},{})
```

**Comment by cypher256** [comment]
WindowBuilder の対応に問題があったため修正しました。
数時間後に反映されます。

2021.04.22

・[github#59] VerifyErrorが発生する
・-Xverify:none 未指定時の lombok エラー対応
・bat, cmd ファイル新規作成時にワークスペースの改行設定に関係なく CRLF をセットする AOP 定義追加

**Comment by orihalcon128** [comment]
正常に動作することを確認しました。
