### ISSUE TITLE
break/continueが訳されている

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#6]
URL:
https://pleiades.io/idea/whatsnew/

問題：
”for と while の強調表示
キャレットをブレークまたは持続するキーワードに配置すると”

ブレーク は break
持続する　は continue

**Comment by cypher256** [comment]
単独で現れる以下の単語を翻訳除外として追加しました。
break
continue

**Comment by mhorioka** [comment]
確認しました
