### ISSUE TITLE
IDEAの更新によるvmoptionsのディレクトリの変更

### ISSUE THREAD

**Issue by SorrowBlue** [cypher256/pleiades.io#60]
IDEAの更新によってvmoptionsのディレクトリが変更されています。
詳しくは下記を見てください。

android studio 4.1[HERE](https://developer.android.com/studio/preview/features#directory-configuration-changes)
IntelliJ IDEA 2020.1 [HERE](https://www.jetbrains.com/help/idea/tuning-the-ide.html?_ga=2.165019455.1890831646.1588892783-2122726634.1572645395#config-directory)

**Comment by cypher256** [comment]
#54 と #58 で対応しましたが、Android Studio は先行で 4.2 以降としていました。
本日 4.2 以降の部分を 4.1 に修正しました。数時間後に反映されます。

2020.06.14
・[IDEA][github#60] vmoptions 位置変更対応で Android Studio 4.2 以降としていたが、4.1 以降に修正
・訳追加修正: Eclipse / IntelliJ, Android Studio

ちなみに JetBrains 製品の日本語マニュアルも公開しています。
https://pleiades.io/help/idea/tuning-the-ide.html#config-directory

**Comment by cypher256** [comment]
Android Studio 4.1 以降の対応に誤りがあったため、Pleiades インストーラーを修正しました。

2020.09.20
・[Eclipse][github#68] ファセット関係の誤訳
・Android Studio 4.1 インストーラー対応
・訳追加修正: Eclipse, STS / IntelliJ, Android Studio
