### ISSUE TITLE
JetBrains IDEの日本語マニュアルのメニューが表示されない

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#61]
2020/6/16 現在

https://www.jetbrains.com/help/idea/ のデザイン変更によるものかもしれませんが、

添付の通り https://pleiades.io/help/idea/ だと左メニューが表示されておりません。

<img width="1137" alt="スクリーンショット 2020-06-16 15 05 37" src="https://user-images.githubusercontent.com/695286/84737553-1bf99580-afe3-11ea-906b-e19a930f5c7a.png">

**Comment by cypher256** [comment]
キャッシュクリア、サーバ再起動で復旧しました。
原因は特定できていませんが、サーバ過負荷になっていた可能性があります。

**Comment by mhorioka** [comment]
ありがとうございます。

問題ないことを確認しました。
