### ISSUE TITLE
Ctrl+クリックするとフリーズする

### ISSUE THREAD

**Issue by sjbiwa** [cypher256/pleiades.io#62]
リンクが見つからない関数等に対して、Ctrl+クリック操作するとフリーズします。
キー入力等、一切の操作を受け付けず、強制終了させるしかなくなります。

環境:
windows10pro
Eclipse 2020/2019/2018/4.8 すべてフリーズします

**Comment by Old-Kevin** [comment]
同じ現象です。
本件解決しましたか？

**Comment by sjbiwa** [comment]
いいえ。
Eclipse は使用しないことに決めました。

**Comment by Old-Kevin** [comment]
ありがとうございます。
IntelliJを使うことにしました。
