### ISSUE TITLE
関数一覧に「======」が表示される

### ISSUE THREAD

**Issue by shirayuki** [cypher256/pleiades.io#63]
お世話になっております。

コンテンツアシスト、呼び出し階層ビューなどあちこちの関数一覧に「======」が表示されます。
translation.propertiesに不要な行が混入しているのが原因です。
```
=\=\=\=\=\=\=
<<<<<<<=.mine
>>>>>>>=.r2492
|||||||=.r2490
```

またpleiades.jarにも不要なファイルが混入しています。
```
translation.properties.mine
translation.properties.r2481
translation.properties.r2482
```

**Comment by cypher256** [comment]
ご指摘のとおり、マージの残骸が混入してしまっていました。
修正しアップ済みです。数時間後に反映されます。
