### ISSUE TITLE
PhpStorm2020.1.2が起動できない

### ISSUE THREAD

**Issue by KatsumiMiyao** [cypher256/pleiades.io#65]
PhpStorm2018.3日本語パッチ適用済みのものから、2020.1版にアップデートをしたところ、アプリケーションが起動画面で固まりました。
再インストールしたら治るかなと思い、何度か試みましたが症状は変わらず起動できません。
このような場合どうすればよろしいのでしょうか？？

OSは、MacOSです。
よろしくお願いします。

**Comment by cypher256** [comment]
Pleiades が最新版 2020.07.02 でない場合は、ダウンロードして再インストールしてください。

それで起動できない場合、
Issue の #54 と #58 および下記を確認いただき、だめでしたらお知らせください。

JetBrains 製品の日本語化マニュアル；「方法2」と「日本語化 FAQ」
https://pleiades.io/pages/pleiades_jetbrains_manual.html#method2

PhpStorm 公式ドキュメント：高度な構成
https://pleiades.io/help/phpstorm/tuning-the-ide.html

その他
vmopitons 設定ファイルに -Dfile.encoding=UTF-8 が指定されている場合は、それを削除してみる。

**Comment by KatsumiMiyao** [comment]
ご回答ありがとうございます。
issure の 54 をやりましたが起動せず、58のPluginsをインストールすることで、無事に起動が出来ました。ありがとうございます。
作業の途中でインストールしたEclipceは、仕事で使わないので削除しておきたいのですが、特段気をつけることはございますでしょうか？？

よろしくお願いします。

**Comment by cypher256** [comment]
使用しない Eclipse は削除するだけで大丈夫です。

**Comment by KatsumiMiyao** [comment]
ありがとうございます。
助かりました。
また、何かあればよろしくお願いします。
