### ISSUE TITLE
phpstorm起動が途中で止まる

### ISSUE THREAD

**Issue by kznrkbys** [cypher256/pleiades.io#66]
【追記1】
昔インストールしたフォルダがあり場所はここで
C:\Users\Koba\.PhpStorm2018.1\config\jp.sourceforge.mergedoc.pleiades
phpstormを削除しても残っていたのでここのpleiadesが悪さしていると予想して、phpstorm2018フォルダごと切り取り移動させて、再度最新のphpstormをインストールしたら動くようになりました。まだしっかりとさわっていないが動いているようです。
私のやり方で大丈夫なのか不安です。
次は日本語化とmacpcにもいれないといけません。・・・先は長い
詳しい方ご回答お願いします。

---------------------------------------------------------------------------------

【初めに投稿した文】
再度phpstormを会社経由で使おうと思い会社内でアカウントを作成してもらいました。

以前2018年頃にphpstormを個人で使っていました。
phpstormは最新のを入れました。

前に使用したphpstormの時に日本語化pleiades?を入れてそれが原因ではないかという記事があります。
なので一度pleiadesを消したい変更したいのですがどこかわかりますか？

その後最新のphpstormに対応したpleiadesを入れても大丈夫なのでしょうか？
教えて下さい。しかも
そのphpstormをリモート用で同じライセンスIDで別のMACpcにも入れる予定でおります。

添付する画像でずっと止まってしまいます泣
![image4](https://user-images.githubusercontent.com/29597477/87508891-50787400-c6ab-11ea-8af0-c9871940d0f8.png)

**Comment by cypher256** [comment]
下記を参照し、Pleiades プラグインのインストーラーから再インストールしてみてください。
#65 PhpStorm2020.1.2が起動できない
