### ISSUE TITLE
Eclipse-202006-All in one CPPフォント設定がおかしい

### ISSUE THREAD

**Issue by Hamada-local** [cypher256/pleiades.io#67]
Eclipse-202006-CPP(Full/Standard)を利用しようとしています。
C/C++ソースを入力するときデフォルトでC/C++エディタが使用されます。
このフォントを変えようと設定しますがエディタに反映されません。
試しにソースをrテキストエディタで開くと反映されたフォントでひらきます。
種々試みた結果、下記の手順で解決できたのですが、何とも不可解です。
1.設定の「外観-色とフォント」の項でテキストフォントを「デフォルトに戻す-反映」を実行します。
2.次に希望するフォント・サイズに設定します。
この手順でフォント設定を一度実行しておくと後は通常通りに設定出来ます。
ーーー＞何故でしょうか？
ちなみにAll in OneでないEclipse-platformをつかいPleiadesで日本語化したものでは何の不都合も生じません。
最初はEclipse本体の問題かと思いましたが、試してみますと何の問題もありませんのでCPPバンドル版の作成時に
何らかの問題を作り込んでいるように思います。

**Comment by cypher256** [comment]
再現を確認できましたが、原因が特定できていません。
ひとまず、ご指摘の方法で対応するか、
下記を設定することで対応してください。

C/C++ > エディター > C/C++ エディター・テキスト・フォント (デフォルト値のオーバーライド: テキスト・フォント)

**Comment by Hamada-local** [comment]
取り敢えずは対応できています。
尚、蛇足ですがAll In OneのCPPとPHPで表示されるツールバーが大きく異なります。
この関連で手を入れている箇所が関わっているのではないでしょうか？？

**Comment by cypher256** [comment]
以下の eclipse.org 標準の CPP パッケージと同じではありませんか？
http://ftp.yz.yamagata-u.ac.jp/pub/eclipse/technology/epp/downloads/release/2020-06/R/
eclipse-cpp-2020-06-R-win32-x86_64.zip

**Comment by Hamada-local** [comment]
失礼しました。
ツールバーは eclipse.org 標準の CPP パッケージと同じでした。
私はこれまでeclipse.orgのplatformを使いPleiadesとCDTをインストールして使っていましたので・・・
