### ISSUE TITLE
eclipseが起動できません。

### ISSUE THREAD

**Issue by andouhiroki76** [cypher256/pleiades.io#69]
https://mergedoc.osdn.jp/のサイトより２０２０年の最新版のEclipseをダウンロードして圧縮ファイルを展開後Eclipse.exeファイルを開こうとすると
『The Edipse executable launcher was unable to locate its companion library』というエラーが出ます。どうしたらいいでしょうか？
OSは、Windows10 proです。
教えてください。
![キャプチャ](https://user-images.githubusercontent.com/68850209/92393775-5fcfe700-f15b-11ea-9aff-4a0e5b4736b9.PNG)

**Comment by cypher256** [comment]
ドライブ直下に 7-Zip で解凍してください。

**Comment by andouhiroki76** [comment]
> ドライブ直下に 7-Zip で解凍してください。

そちらも試したのですが、開けませんでした。どうしたらいいでしょうか？

**Comment by cypher256** [comment]
#40 を参照してください。
