### ISSUE TITLE
「Git」ページで現在完了形の have が「持っている」という意味になっている

### ISSUE THREAD

**Issue by shuuji3** [cypher256/pleiades.io#7]
こんにちは。誤訳の報告です。

- 対象日本語ページ: [Git リモートのパスワードを設定する](https://pleiades.io/help/idea/using-git-integration.html#set-passwords-for-git-remotes)
- 対応する原文のページ: [Set passwords for Git remotes](https://www.jetbrains.com/help/idea/using-git-integration.html#set-passwords-for-git-remotes)

上記のページで「パスワードポリシーを設定しましたをお持ちの場合」と翻訳されている部分ですが、現在完了形の「have」を「持っている」という意味で誤訳してしまっているようです。

**Comment by cypher256** [comment]
インラインのリンク部分を別翻訳する処理を行っていたため不正となっていました。
翻訳後処理で補正するように修正しました。

**Comment by shuuji3** [comment]
なるほど、そのような経緯があったのですね。
素早いご対応ありがとうございます。

**Comment by shuuji3** [comment]
修正を確認しました。
