### ISSUE TITLE
脱字

### ISSUE THREAD

**Issue by t11em** [cypher256/pleiades.io#70]
お世話になっております。
[こちらのページ](https://pleiades.io/help/clion/qt-tutorial.html#configure-cmakelists)の一部に脱字が見つかったので報告します。

Expected：QMake
Actual：Qake

![20200917-014258](https://user-images.githubusercontent.com/26321813/93367057-fbadd100-f886-11ea-9a1e-1e9f58080850.png)

**Comment by cypher256** [comment]
原文は下記の部分が Qt なっており、翻訳誤りのため、修正しました。

> Expected：QMake
> Actual：Qake

修正前：
find_package を正常に実行するには、Qakeインストールの場所をCMakeに指示する必要があります。
修正後：
find_package を正常に実行するには、Qtのインストール場所をCMakeに指示する必要があります。
