### ISSUE TITLE
Pleiades 2020-09 コンパイラー準拠レベルを15にできない

### ISSUE THREAD

**Issue by happyhills** [cypher256/pleiades.io#71]
Pleiades 2020-09 で、インストール済のJREにjdk-15.0.1を追加しました。
コンパイラー準拠レベルを15にしたいのですが、できません。

**Comment by cypher256** [comment]
このプラグインを Eclipse マーケットプレースから入れてください。
https://marketplace.eclipse.org/content/java-15-support-eclipse-2020-09-417

Pleiades All in One としては 2020-12 から対応予定です。

**Comment by happyhills** [comment]
サポートがまだだったのですね。情報ありがとうございます。助かりました。
こちらではオールインワンをそのまま使う運用になっているので、2020-12を待つことにします。
