### ISSUE TITLE
JavaScriptエディターが消えた（Eclipse 2020）

### ISSUE THREAD

**Issue by Riopika** [cypher256/pleiades.io#72]
最新のEclipseをインストールしましたがJavaScriptエディターが存在せず、JavaScriptファイルを開いても全ての文字が真っ黒で非常に見にくい。
どうなっているのでしょうか。
![ファイルの関連付け_エディターの選択](https://user-images.githubusercontent.com/60454400/100328804-462e9500-3010-11eb-9cda-dd04896cf415.jpg)

**Comment by cypher256** [comment]
汎用テキストエディターに
デフォルト関連付けして開いてください。

**Comment by Riopika** [comment]
> 汎用テキストエディターに
> デフォルト関連付けして開いてください。

色は付きましたが元々の色と違っており、色が薄いためとても見にくいです。

**Comment by cypher256** [comment]
元の JS エディターは廃止されました。
Pleiades ではなく Eclipse の仕様です。

**Comment by Riopika** [comment]
> 元の JS エディターは廃止されました。
> Pleiades ではなく Eclipse の仕様です。

承知しました。
ありがとうございました。
