### ISSUE TITLE
2018以前のPleiades All in Oneの中にあるCode Recommendersプラグインを削除してほしい

### ISSUE THREAD

**Issue by noblevalley** [cypher256/pleiades.io#73]
Pleiades All in Oneの2018を使用していますと、ピリオドを打つたび以下のエラーメッセージが出てきます。

--ここから
Failed to Download Index
Code Recommenders cannot download its model repository index.
Please make sure that you are connected to the Internet.
If so, check our FAQ for help on resolving this issue.
If the problem persists, please file a bug with the Eclipse Code Recommenders project.
Silently ignore future download failures
--ここまで

調べてみますとプロジェクト自体が終了してメンテナンスもされていないみたいです。
エラーメッセージを出さないようにチェックを入れているのですが、
動かないプラグインを入れていてもディスクやメモリが消費されてもったいないです。
お手数ですが、Code Recommendersプラグインの削除をお願いします。

**Comment by cypher256** [comment]
本家 Eclipse と同じく最新版のみメンテナンスしています。
申し訳ないですが、過去リリースはメンテナンスしていません。

**Comment by noblevalley** [comment]
そうなんですね。残念ですが、承知しました。
closeいたします。ご回答ありがとうございました。

上に書いてあるチェックを入れて無視をする方法で対応するか
自力でプラグイン削除する方法で対応するかぐらいでしょうね。
