### ISSUE TITLE
GoLandドキュメントの誤字

### ISSUE THREAD

**Issue by Le0tk0k** [cypher256/pleiades.io#74]
https://pleiades.io/ のGoLandのページのサイドバーに、

- 非囲碁テクノロジー

という項目がありますが、「非囲碁」は「Go以外」ではないでしょうか。

<img width="376" alt="スクリーンショット 2020-12-16 14 48 43" src="https://user-images.githubusercontent.com/62293842/102310183-d75cb000-3fad-11eb-9eb5-0e45ea9cf676.png">

**Comment by cypher256** [comment]
おぉ。。。修正しました。
ブラウザをスーパーリロードするか、24 時間以内に反映されます。

**Comment by Le0tk0k** [comment]
ありがとうございます！
確認できました。
