### ISSUE TITLE
Pull Resultの誤訳

### ISSUE THREAD

**Issue by shirayuki** [cypher256/pleiades.io#79]
お世話になっております。

Pull Resultがプル・リクエストと訳されていますので、修正をお願いします。

Pull\ Result\ for\ {0}={0} のプル・リクエスト

**Comment by cypher256** [comment]
Pleiades の誤訳を修正しました。
次回リリース時に反映します。

**Comment by cypher256** [comment]
リリースしました。
数時間後に反映されます。

2021.04.21

・[github#80] Checkstyleでエラーが発生する
・[github#79] Pull Resultの誤訳
・[github#59] VerifyErrorが発生する
・Java 要素ホバー時に表示される Java 14 以降の日本語 Javadoc URL 自動設定対応 (ワークスペース作成時)
・ダーク系テーマ Windows で問題ビューなどのヘッダー罫線、設定ダイアログの罫線を目立たなくする AOP 定義追加
・エディター上の印刷マージン線アルファを薄くなるように AOP 定義追加
・ニーモニック処理で ConcurrentModificationException が発生する問題を修正
・クイック・アクセスのダイアログの説明が翻訳されない場合の対応
・パッケージ・エクスプローラーでプロジェクトが Servers のみの場合、ビュー内に新規メニューを表示
・訳追加修正: Eclipse, PDT, STS, Subclipse, WindowBuilder, Batch Editor

**Comment by shirayuki** [comment]
ありがとうございます。
