### ISSUE TITLE
CLion 2018.3 what's new へのコメント

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#8]
URL:https://pleiades.io/clion/whatsnew/

1) フードの下でCLionで何が起こっているのか
英語：Under the hood
提案：内部的に

2) まずPreferencesでリモートツールチェーンを作成します|ビルド、実行、デプロイ |ツールチェーン
英語：first create a remote toolchain in Preferences | Build, Execution, Deployment | Toolchains. 
提案：まずPreferences|ビルド、実行、デプロイ |ツールチェーン でリモートツールチェーンを作成します

3) 新しい何でも実行する
英語：New Run Anything
提案：新しいなんでも実行

4) どこでも更新された検索
英語：Updated Search Everywhere
提案：更新されたどこでも検索

5) コンパイルデータベース
英語：コンパイルデータベース
提案: Compilation database  （あまり知られていないtechnical termなので英語のままのほうがいいかも）

6) 貨物ユニットテスト
英語：cargo unit testing
提案: cargo ユニットテスト (cargoはRustの機能なので訳さない）

**Comment by cypher256** [comment]
> フードの下でCLionで何が起こっているのか
> 英語：Under the hood
> 提案：内部的に

後翻訳で対応しました。(サイト全体で類似 6 箇所該当)

> まずPreferencesでリモートツールチェーンを作成します|ビルド、実行、デプロイ |ツールチェーン
> 英語：first create a remote toolchain in Preferences | Build, Execution, Deployment | Toolchains.
> 提案：まずPreferences|ビルド、実行、デプロイ |ツールチェーン でリモートツールチェーンを作成します

「Preferences | Build, Execution, Deployment | Toolchains」
をひとまとまりの単語のように扱うように翻訳前処理を修正しました。

「まずPreferences」
の Preferences は OS によりブラウザ表示時に動的変化するようになっているみたいで、下記のように対応しました。
Windows、Linux の場合: Settings → 設定
Mac の場合: Preferences → 環境設定

> 新しい何でも実行する
> 英語：New Run Anything
> 提案：新しいなんでも実行

訳追加しました。

> どこでも更新された検索
> 英語：Updated Search Everywhere
> 提案：更新されたどこでも検索

訳追加しました。

> コンパイルデータベース
> 英語：コンパイルデータベース
> 提案: Compilation database （あまり知られていないtechnical termなので英語のままのほうがいいかも）

[Cc]ompilation [Dd]atabase を翻訳禁止ワードに追加ました。
合わせて単独の bear を翻訳禁止ワードに追加ました。

> 貨物ユニットテスト
> 英語：cargo unit testing
> 提案: cargo ユニットテスト (cargoはRustの機能なので訳さない）

翻訳除外ワードに追加しました。
(Cargo は追加済みでしたが、cargo を追加)

**Comment by mhorioka** [comment]
ありがとうございます。確認しました。
