### ISSUE TITLE
Checkstyleでエラーが発生する

### ISSUE THREAD

**Issue by orihalcon128** [cypher256/pleiades.io#80]
・環境
eclipse-java-2021-03-R-win32-x86_64.zip
pleiades-win-2021.03.28.zip
net.sf.eclipsecs-updatesite_8.37.0.202104012125.zip

・eclipse.iniに追加したオプション
-Xverify:none
-javaagent:dropins/Pleiades/eclipse/plugins/jp.sourceforge.mergedoc.pleiades/pleiades.jar

・エラーが発生する手順
(1) ウィンドウ→設定→Checkstyle
(2) Google Checksをダブルクリックする

**Comment by cypher256** [comment]
CheckStyle のメタデータを訳してしまっている部分があったため修正しました。
数時間後に反映されます。

2021.04.21

・[github#80] Checkstyleでエラーが発生する
・[github#79] Pull Resultの誤訳
・[github#59] VerifyErrorが発生する
・Java 要素ホバー時に表示される Java 14 以降の日本語 Javadoc URL 自動設定対応 (ワークスペース作成時)
・ダーク系テーマ Windows で問題ビューなどのヘッダー罫線、設定ダイアログの罫線を目立たなくする AOP 定義追加
・エディター上の印刷マージン線アルファを薄くなるように AOP 定義追加
・ニーモニック処理で ConcurrentModificationException が発生する問題を修正
・クイック・アクセスのダイアログの説明が翻訳されない場合の対応
・パッケージ・エクスプローラーでプロジェクトが Servers のみの場合、ビュー内に新規メニューを表示
・訳追加修正: Eclipse, PDT, STS, Subclipse, WindowBuilder, Batch Editor

**Comment by orihalcon128** [comment]
Checkstyleが動作することを確認しました。
