### ISSUE TITLE
pleiadesを付加すると内部ブラウザが開かない。

### ISSUE THREAD

**Issue by Hamada-local** [cypher256/pleiades.io#81]
eclipse-jee-2021-03-R-win32-x86_64.zipを展開した結果を使う。
1.展開結果(英語版)を起動し、パースペクティブJavaEEを設定する。
　表示された「Webブラウザを起動」アイコンをクリックするとWebブラウザのblankページが開かれる。
2.展開結果にpleiades-win.zipを展開して日本語化する。
3.日本語化したEclipseを起動する。
　表示された「Webブラウザを起動」アイコンをクリックするとWebブラウザがエラーの形で小さく表示される。
4.eclipse.iniの最後の2行（日本語化の設定）を削除して行うと正常に動作する。
以上の結果、pleiadesを実行することでWebブラウザ起動アイコンに関わる何かを無くしているようです。

**Comment by Hamada-local** [comment]
追記です。
Pleiades All in One EclipseのJavaをダウンロードして確かめてみました。
同じ現象になります。
Pleiadesの日本語化処理がおかしくしているようですね。

**Comment by Hamada-local** [comment]
更に追記です。
Pleiades All in One Eclipseの2020-12　Javaを使って確かめました。
Webブラウザは正常に表示されました。urlに"about:blank"が表示されます。
前記の正しく表示されない時urlはエラーログの内容から見てnullになっているようです。
pleiades.jarの旧バージョンの入手が出来ないのでどの時点でおかしくなったのか確かめられませんが
pleoades.jarが悪さをして居るように思います。

**Comment by cypher256** [comment]
ご指摘どおり、about:blank の時に url が null となっており、Pleiades で NPE が発生していました。
Pleiades 本体を修正し、リリースしました。
Pleiades All in One は次回リリース時に反映予定です。

**Comment by Hamada-local** [comment]
有り難うございました。
修正結果を確認しました。
