### ISSUE TITLE
C/C++ Edition で Workspace に置いたフォルダをリンクするとソースファイル表示が行えない

### ISSUE THREAD

**Issue by Majesty-98** [cypher256/pleiades.io#82]
【対象】
Eclipse 2021 以前 64bit版全ての C/C++ Edition
32bit 版は問題ない

【問題】
C/C++ Edition で Workspace に置いたフォルダをリンクするとソース表示が行えない。
Ultimate Edition ではソース表示が行える。

【再現方法】
C/C++ Edition で 
①Workspase に Hello World C++ プロジェクト(test)を作成する
②test フォルダ内生成された src フォルダを 上位フォルダ（workspace) に移動する
　※パッケージエクスプローラー部から src フォルダが消える
③インポート処理を行う
　一般 → ファイルシステム → 【次へ>】
　
　次のディレクトリから に workspace の src フォルダ
　src フォルダ をチェック
　【拡張>>】で開く
　■Create links in workspace
　□Create vertual folder
　■リンク・ロケーションを相対で作成 [PROJECT_LOC]（WORKSPACE_LOC等でもng）
　【完了】
④パッケージエクスプローラー部のsrc\test.cpp を開くと
　Ultimate Edition ではソース表示が行えるが
　C/C++ Edition では「ファイル /test/test.cpp が存在しません」と表示される
　C/C++ Edition でパッケージエクスプローラー部の「次で開く」→「システムエディタ」で開くと該当のファイルを開くことはできる。

**Comment by Majesty-98** [comment]
**確認結果**

ご教授いただいた対応方法で、無事リンクフォルダを作成した後、ファイルのオープン、デバッグ機能なども行えることを確認しました。

迅速な回答ありがとうございました。

ーーーーーーーーーーーーーーー
もう一件、よく原因がわからない現象があります。再現性は高いのですがどういう場合に再現できるか特定できてません。再現方法がわかったらまた別途質問させていただきます。

現象は、ビルドすると プロジェクトフォルダ（makefile.def などがあるフォルダ）に -dDpt と spec.o ファイルが生成されます。spec.c ファイルは src フォルダ内には無いし、Dpt マクロを定義している部分もありません。 

プラグインのどれかでspec.c をコンパイルするような処理がありその残骸っぽいことまで調べたのですが時間がなくて調べられていません。（Eclipseフォルダを全検索かけるとspec を扱っているようなファイルが出てくるまでは確認）

取り敢えず、優先度が低いのでまた調査できたら質問させていただきます。

**Comment by cypher256** [comment]
> ### 対応
> 根本的には Eclipse Zip Editor プラグインの問題ですが、Pleiades All in One の対応として
> 次回リリースで、Ultimate、Java Edition 以外のプロジェクト・エクスプローラーの Zip アーカイブ機能を
> OFF にする予定です。

2021-06.20210620 リリース済み
https://mergedoc.osdn.jp/pleiades_distros2021.html#changes

**Comment by Majesty-98** [comment]
2021-06.20210620 リリースにて改善されていることを確認しました。
ありがとうございました。
