### ISSUE TITLE
半角の「￥」記号の扱いでエラーにならないケースがある

### ISSUE THREAD

**Issue by chida-sss** [cypher256/pleiades.io#83]
【対象】
Eclipse 2020-12 Java(Standard Edition/Windows)

【問題】
Javaのコンソールアプリケーションにて、
下記ソースコードがエラーにならず、そのままコンソールに出力される。
public class Sample {
	public static void main(String[] args) {
		System.out.println("¥dddddd");
		System.out.println("お会計は¥800です。");
		System.out.println("お会計は¥です。");
		System.out.println("¥¥");
	}
}

【再現方法】
本家サイトのEclipse 2020-12(Eclipse IDE for Java Developers)ではエラーとなる。

**Comment by cypher256** [comment]
ワークスペースのエンコーディングのデフォルト設定が
本家は MS932、
Pleiades All in One は他の箇所も含め UTF-8 に統一しているため、そうなります。

MS932 → エラー
UTF-8 → エラーにならない

設定 > 一般 > ワークスペース > テキスト・ファイル・エンコードから変更できます。

**Comment by chida-sss** [comment]
大変失礼いたしました。
丁寧なご返信ありがとうございます。
本件クローズさせていただきます。
