### ISSUE TITLE
Eclipseの内部ブラウザの不備

### ISSUE THREAD

**Issue by Hamada-local** [cypher256/pleiades.io#85]
Pleiadesとは関係ない話ですが・・・
Eclipseの内部ブラウザではURLパラメーターに日本語を含めると正しく渡りません。
色々トライしたんですが上手く実現することが出来ませんでした。
勿論、外部ブラウザを使用すると何の問題はないのですが・・・

**Comment by cypher256** [comment]
実行環境: Windows 10 最新、Eclipse 2021-06

現状、Eclipse の内部ブラウザの実装は下記のようになっているため、
IE 11 (Windows 8) で動作確認したい場合を除き、避けたほうが良いかと思います。

Mozilla/5.0 (Windows NT 6.2; Win64; x64; Trident/7.0; rv:11.0) like Gecko
* Trident/7.0 → IE 11
* Windows NT 6.2 → Windows 8

Pleiades All in One でも 2021-06 から外部ブラウザがデフォルトになっています。
（上記以外に、macOS で localhost でも https でないと開けなくなったのが致命的なため）

**Comment by Hamada-local** [comment]
了解しました。
