### ISSUE TITLE
DataGripのチュートリアル/Google CloudSQL インスタンスに接続するのMySQLのsocketFactoryが間違っている

### ISSUE THREAD

**Issue by polyomino-24** [cypher256/pleiades.io#88]
https://pleiades.io/help/datagrip/connect-to-google-cloud-sql-instances.html#step-1-add-the-cloud-sql-connector-to-the-driver
で
MySQLのsocketFactoryとして
```
socketFactory = com.google.cloud.sql.postgres.SocketFactory
```
が指定されていますが
```
socketFactory = com.google.cloud.sql.mysql.SocketFactory
```
の誤りです

**Comment by cypher256** [comment]
ありがとうございます。
原文誤りのため、JetBrains に報告しました。

https://www.jetbrains.com/help/datagrip/connect-to-google-cloud-sql-instances.html#step-1-add-the-cloud-sql-connector-to-the-driver

**Comment by polyomino-24** [comment]
ありがとうございます。原文がどこにあるか見当たらずこちらのissueに書いてしまいました。お手数おかけします。
