### ISSUE TITLE
CLion プロジェクトフォーマットページの誤訳

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#89]
日：
https://pleiades.io/help/clion/project-models.html

英：
https://www.jetbrains.com/help/clion/project-models.html

- 現状

Open Project　が 「開いた事業」　と訳されている

- 改善案

「プロジェクトを開く」

**Comment by cypher256** [comment]
ありがとうございます。
原文に改行 LF が含まれる場合に、「プロジェクト」が「事業」となる場合があったため修正しました。

対象ページ (同様の問題がある他のページも修正)
https://pleiades.io/help/clion/project-models.html
https://pleiades.io/help/idea/gradle-jvm-selection.html#jdk_existing_project
https://pleiades.io/help/rider/Refactorings__Rename.html#using-the-refactoring-for-different-c-entities

**Comment by mhorioka** [comment]
ありがとうございます
