### ISSUE TITLE
https://pleiades.io/ から新機能ページへのリンク

### ISSUE THREAD

**Issue by mhorioka** [cypher256/pleiades.io#9]
バグではないですが、現状

1. https://pleiades.io/　の個別の製品からwhat's new へのリンクがない（たぶん）
2. https://pleiades.io/idea/whatsnew/　がtwitter等からのdirect linkでないと見つけにく

https://pleiades.io/　からwhat's new （新機能）へのリンクがあると多くのユーザの目に付きやすいのではと思いました。

**Comment by mhorioka** [comment]
そこにあったんですね。SNSとの並びだったせいか気づきませんでした。すでにボタンがあるのであれば、個人的には対応は不要でもかまいません。

**Comment by cypher256** [comment]
おっしゃるとおり、SNS の並びはおかしいので、少しの修正ですが、新機能は左端、SNS系ボタンは右端にしました。現状、"Intellij 新機能" での Google 検索でもクリックされやすい順位で、情報が必要な方からの流入も問題ないと思われるため、本 issue はこれで終了します。
