### ISSUE TITLE
英語表示の場合、PHP project の Project Explorer でファイル名がパスで表示される

### ISSUE THREAD

**Issue by tokunaga1** [cypher256/pleiades.io#91]
PHP project 内でファイルを作成すると、

日本語表示の場合、下図 `(7)` のようにファイル名 (_index.php_) だけが表示されます。

![20211009T033319](https://user-images.githubusercontent.com/49953164/136609700-5d875675-e2d1-4b9a-bd06-f483d632e414.png)

一方、英語表示の場合、下図 `(10)` のようにパス (_L/p1/index.php_) として表示されます。

![20211009T033407](https://user-images.githubusercontent.com/49953164/136609724-2246773e-853f-40d7-8cb3-578cacdbe5b0.png)

英語表示でも、日本語表示の `(7)` のようにファイル名だけを表示させるにはどうしたら良いのでしょう？

ちなみに、
日本語表示で project を作成した後に英語表示に切り替えても、
project explorer ではファイル名のみが表示されました。

英語表示の環境であっても、
project を生成した際の日本語環境の設定が効いているみたいです。

日本語、英語の切り替えは以下の手順で行っています。
切り替えた後は、eclipse.exe -clean.cmd にて起動。

---

下記 Pleiades All in One Eclipse を download。

* pleiades-2021-06-php-win-64bit-jre_20210629.zip
* Windows 64bit
* PHP
* Full Edition

### eclipse.ini を編集せずに、eclipse を起動。

pleiades/eclipse/eclipse.ini `(1)`

![20211009T024742](https://user-images.githubusercontent.com/49953164/136610863-b1803a8c-241e-47cb-bbc8-cb6220a5da3f.png)

### プロジェクトを作成
`(2)`,`(3)`,`(4)`

![20211009T025650](https://user-images.githubusercontent.com/49953164/136610883-952e447d-fea2-4664-9971-f1dbdb18c909.png)

![20211009T025717](https://user-images.githubusercontent.com/49953164/136610892-6a0fdfc4-6d6c-485e-8d49-5e1196e59150.png)

![20211009T025755](https://user-images.githubusercontent.com/49953164/136610900-8e73510b-30cd-41f7-a339-275e5082f5d4.png)

### ファイルを作成
`(5)`,`(6)`,`(7)`

![20211009T025932](https://user-images.githubusercontent.com/49953164/136610931-6a74f7a3-06bd-439c-a4a4-a584130857e9.png)

![20211009T030030](https://user-images.githubusercontent.com/49953164/136610940-e0618cc7-12cd-461f-b670-c619f7568f76.png)

![20211009T030102](https://user-images.githubusercontent.com/49953164/136610946-46f83483-5cee-404c-bbf6-07dba5ee611e.png)

### eclipse.ini で `(8)` の行頭に `;` を付けて comment out
英語表示に切り替え

![20211009T030134](https://user-images.githubusercontent.com/49953164/136610990-f2c70c1d-a3df-41ec-8aca-73d079b13b06.png)

### プロジェクトを作成
`(9)`

![20211009T030858](https://user-images.githubusercontent.com/49953164/136610999-7ab1ade2-4790-4021-858d-c359f90700fa.png)

### ファイルを作成
`(10)`

![20211009T031000](https://user-images.githubusercontent.com/49953164/136611027-87f3bfa6-ef63-4737-aaaa-93ed7b9efbf2.png)

**Comment by cypher256** [comment]
詳細な状況説明ありがとうございます。下記を設定してみてください。

Project Explorer
→ 右上 ︙ クリック
→ Filters and Customization...
→ Content タブ
→ Zip Archive チェックをはずす
→ OK ボタン

**Comment by tokunaga1** [comment]
回答ありがとうございます。

仰る方法で表示が切り替わることを確認できました。
ありがとうございました。

![20211010T133431](https://user-images.githubusercontent.com/49953164/136682412-ccaf2f25-f122-4ab4-8f87-2303c8578090.png)

![20211010T133513](https://user-images.githubusercontent.com/49953164/136682501-7c428e53-42fc-4509-a134-fe20a5012e3b.png)

![20211010T133539](https://user-images.githubusercontent.com/49953164/136682426-f4f98305-7e06-46a5-aded-b3f74c728abe.png)
