### ISSUE TITLE
eclipseをプラグインを使って日本語化すると起動ができなくなる。

### ISSUE THREAD

**Issue by timobol** [cypher256/pleiades.io#93]
### 前提・実現したいこと

eclipseの日本語化をしたく、質問させていただきます。
まず下記のサイトを参考にJDKをインストールしました。
環境変数でPATHの設定も行いました。
[https://eng-entrance.com/java-install-jdk-windows](https://eng-entrance.com/java-install-jdk-windows)
バージョンは17.0.1です。
![](https://teratail-v2.storage.googleapis.com/uploads/contributed_images/264ff7f9c131a753173e24b5502739a9.png)
その後、下記のサイトを参考にしてEclipse IDE for Enterprise Java and Web Developerをeclipse installerを使ってインストールしました。
[https://www.kkaneko.jp/tools/win/eclipse.html](https://www.kkaneko.jp/tools/win/eclipse.html)
![](https://teratail-v2.storage.googleapis.com/uploads/contributed_images/10f7cccd1f40653bb13a1291b6a56cec.png)

### 発生している問題・エラーメッセージ
インストールは成功し、英語版での起動は特に問題なくできました。
その後下記のサイトからPleiades プラグインをダウンロードしました。
日本語化のためにsetup.exeを実行し日本語にした後、一度eclipse.exe -clean.cmdを実行し、日本語でしっかりeclipseが起動したのですが、一度閉じて再度起動しようとすると、下記の画像のように「java was started but returned exit code=1」から始まるメッセージが出てしまい起動が出来なくなってしまいます。
（1度目の起動）
![](https://teratail-v2.storage.googleapis.com/uploads/contributed_images/a9f99f91ad0a8e86e5d7e76a26b2a258.png)

（2度目の起動）
![](https://teratail-v2.storage.googleapis.com/uploads/contributed_images/f7bf06d71f94fe11eb1f0b996452d96e.png)

### 試したこと

様々なサイトを参考に調べているのですが、eclipse.iniに下記のようにjavaw.exeまでのPATHを追記するとうまくいった例があるようなのですが、私も同様に追記してみたもののeclipse.exeをダブルクリックすると下記画像のようなメッセージが出てきてしまいます。
※スタートメニューから起動すると、先ほどの「java was started but returned exit code=1」のメッセージが表示されます。
（eclipse.iniに追記した部分）
```ここに言語名を入力
-vm
C:\Program Files\Java\jdk-17.0.1\bin\javaw.exe
```
![](https://teratail-v2.storage.googleapis.com/uploads/contributed_images/fcad19e5700cc22ece0dcdb9f3fe0e90.png)

ログを確認すると、下記のような内容が記載されていました。

（1637325873043.log）
```ここに言語名を入力
!SESSION Fri Nov 19 21:44:33 JST 2021 ------------------------------------------
!ENTRY org.eclipse.equinox.launcher 4 0 2021-11-19 21:44:33.092
!MESSAGE Could not find extension: reference:file:org.eclipse.osgi.compatibility.state_1.2.500.v20210730-0750.jar
!ENTRY org.eclipse.equinox.launcher 4 0 2021-11-19 21:44:34.057
!MESSAGE Exception launching the Eclipse Platform:
!STACK
java.lang.ClassNotFoundException: org.eclipse.core.runtime.adaptor.EclipseStarter
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:656)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

### 補足情報（FW/ツールのバージョンなど）

OSはWindows10です。
JDKのバージョンは17.0.1です。
eclipsはEclipse IDE for Enterprise Java and Web Developerをインストールしています。

**Comment by cypher256** [comment]
eclipse.ini から下記を削除してみてください。起動すると追加されてまうみたいです。
```
-install
@launcher.dir/
```

**Comment by timobol** [comment]
上記の方法で問題は解決できました！
ありがとうございます。
