### ISSUE TITLE
Linuxでini編集後Eclipseが起動できなくなる。

### ISSUE THREAD

**Issue by sakaki-makoto** [cypher256/pleiades.io#94]
iniをPleiadesのreadme通りに編集したあと次のようなエラーが出て起動できません。環境はFedora35です。
<pre>
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f6f724910ec, pid=433722, tid=433723
#
# JRE version: OpenJDK Runtime Environment (16.0.2+7) (build 16.0.2+7-67)
# Java VM: OpenJDK 64-Bit Server VM (16.0.2+7-67, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, linux-amd64)
# Problematic frame:
# C  0x00007f6f724910ec
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" 

</pre>
Javaなどの情報は
java 17.0.1 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
です

OSはFedora Linux35でEclipseのバージョンはeclipse-java-2021-09-R-linux-gtk-x86_64です。

ちなみにiniは
<pre>
-startup
plugins/org.eclipse.equinox.launcher_1.6.300.v20210813-1054.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.300.v20210828-0802
-product
org.eclipse.epp.package.java.product
-showsplash
org.eclipse.epp.package.common
--launcher.defaultAction
openFile
--launcher.defaultAction
openFile
--launcher.appendVmargs
-vm
plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_16.0.2.v20210721-1149/jre/bin
-vmargs
-Dosgi.requiredJavaVersion=11
-Dosgi.instance.area.default=@user.home/eclipse-workspace
-Dsun.java.command=Eclipse
-XX:+UseG1GC
-XX:+UseStringDeduplication
--add-modules=ALL-SYSTEM
-Dosgi.requiredJavaVersion=11
-Dosgi.dataAreaRequiresExplicitInit=true
-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true
-Xms256m
-Xmx2048m
--add-modules=ALL-SYSTEM
-javaagent:Eclipseディレクトリ/plugins/jp.sourceforge.mergedoc.pleiades/pleiades.jar

</pre>

Eclipseディレクトリは絶対パスにしています。-Xverify:noneはエラーが増えるのでつけませんでした。

**Comment by sakaki-makoto** [comment]
追記します。
OSはFedora Linux35でEclipseのバージョンはeclipse-inst-jre-linux64です。

**Comment by cypher256** [comment]
eclipse.ini の下記 2 行を削除し、インストールされている java 17.0.1 2021-10-19 LTS を使用しても同じですか？

-vm
plugins/org.eclipse.justj.openjdk.hotspot.jre.full.linux.x86_64_16.0.2.v20210721-1149/jre/bin

**Comment by sakaki-makoto** [comment]
動きました。ありがとうございます。
