### ISSUE TITLE
Spring Data JDBCリファレンスの一部で「集約」と訳すべき箇所が「集計」と訳されている

### ISSUE THREAD

**Issue by dkurata38** [cypher256/pleiades.io#95]
# Spring Data JDBCリファレンスの一部で「集約」と訳すべき箇所が「集計」と訳されている

いつも翻訳ありがとうございます。

## 指摘箇所

https://spring.pleiades.io/spring-data/jdbc/docs/current/reference/html/#jdbc.entity-persistence

> CrudRepository.save(…) メソッドを使用して、集計を保存できます。

## 期待される翻訳結果

> CrudRepository.save(…) メソッドを使用して、集約を保存できます。

読んでくださってありがとうございます。

**Comment by cypher256** [comment]
ありがとうございます。
全般的に aggregate が集計になっている部分を集約に修正しました。

**Comment by dkurata38** [comment]
@cypher256 
修正ありがとうございます。
直っていることを確認しました！
