### ISSUE TITLE
誤訳：詩篇

### ISSUE THREAD

**Issue by yh1224** [cypher256/pleiades.io#96]
https://pleiades.io/help/phpstorm/using-psalm.html#running-tool-in-batch-mode ([オリジナル](https://www.jetbrains.com/help/phpstorm/using-psalm.html#running-tool-in-batch-mode))

Psalm という固有名詞が和訳されてしまっているようです。

- 詩篇 -> Psalm

**Comment by cypher256** [comment]
ありがとうございます。
固有名詞として登録し、全体に反映しました。
