### ISSUE TITLE
CheckStyleの指摘反映方法について

### ISSUE THREAD

**Issue by Riopika** [cypher256/pleiades.io#98]
以前のチェックスタイルは警告メッセージが表示されているところへマウスカーソルを当てるとポップアップで警告メッセージの表示と修正内容を自動でしてくれるリンクのようなものが有りましたが、最新のものはこのリンクが有りません。
仕様でしょうか？
![旧](https://user-images.githubusercontent.com/60454400/147878311-e519051d-5b14-44ff-ac24-10d00bc7f50e.jpg)
![最新](https://user-images.githubusercontent.com/60454400/147878312-0cf06a7b-68f2-4b3e-af9f-eefb8ef9230c.jpg)

**Comment by cypher256** [comment]
確認したところ、Checkstyle プラグインのクイックフィックス動作は下記でした。
- Checkstyle 8.35 表示される
- Checkstyle 8.36 以降、表示されない

Checkstyle Github Issue がありますが、今のところ対応されていないようです。
https://github.com/checkstyle/eclipse-cs/issues/315

**Comment by Riopika** [comment]
承知しました。
ありがとうございました。
